#!/bin/sh
set -eu
python3 verify_final_source.py
python3 runtime_config_compat.py
trap 'rm -f index.html' 0
python3 build_final.py
rm -f index.html
trap - 0
python3 p2_finalize.py
python3 test_p2_output.py
python3 security_finalize.py
python3 backup_security_finalize.py
python3 security_reveal_ui_finalize.py
# Canonical compatibility scaffolding. Legacy status/loading paths are retained
# only as build-time markers and are stripped from the shipped runtime by v6.
python3 credential_template_initial_finalize.py
python3 credential_status_ui_finalize.py
python3 account_asset_client_context_finalize.py
python3 assets_all_clients_finalize.py
python3 credential_status_loading_finalize.py
python3 account_asset_value_typography_finalize.py
python3 test_credential_status_ui_output.py
python3 test_account_asset_client_context_output.py
python3 test_credential_status_loading_output.py
python3 test_account_asset_value_typography_output.py
python3 account_login_identifier_v2_finalize.py
# Generate the final unlock + scalar-value credential reveal controller in one
# build stage. This replaces the historical persisted v3 -> v4 intermediate chain.
python3 credential_secure_reveal_finalize.py
python3 test_security_hotfix_output.py
python3 test_security_reveal_ui_output.py
python3 test_credential_template_initial_output.py
python3 test_account_login_identifier_output.py
python3 test_credential_unlock_v4_output.py
python3 credential_client_detail_v4_finalize.py
python3 test_credential_client_detail_v4_output.py
python3 test_assets_all_clients_output.py
python3 test_workspace_state_secret_hard_guard.py
python3 test_backup_security_output.py
python3 test_vercel_security_headers.py
python3 test_rpc_surface_hardening.py
python3 test_session_security_migrations.py
python3 cloud_save_queue_finalize.py
python3 test_cloud_save_queue_output.py
python3 ui_action_finalize.py
python3 test_ui_action_output.py
python3 remove_login_material_view_finalize.py
python3 test_remove_login_material_view_output.py
# Consolidated credential UI pipeline: controller includes memory-only safe-summary
# prefetch; runtime includes v6 cleanup, atomic placeholder gate, and event liveness.
python3 credential_ui_v5_finalize.py
python3 test_credential_ui_v5_output.py
python3 credential_ui_v6_finalize.py
python3 test_credential_ui_v6_output.py
python3 http_only_session_finalize.py
python3 test_http_only_session_output.py
python3 client_detail_return_finalize.py
python3 test_client_detail_return_output.py
python3 module_home_navigation_finalize.py
python3 test_module_home_navigation_output.py
# Final DOM-liveness repair: a reveal marker is valid only when the real per-field
# eye button still exists. This prevents placeholder scrubs from leaving stale
# markers that suppress the v5 scalar reveal control.
python3 credential_eye_self_heal_finalize.py
python3 test_credential_eye_self_heal_output.py
node --check api/crm.js
GROWTHOPS_SUPABASE_SECRET_KEY=sb_secret_test_http_only_ci node test_http_only_session_api.js
node test_cloudflare_p2b_api.mjs
node test_cloudflare_p3p4_attack_regression.mjs
python3 test_p5_sensitive_rpc_revocation.py
python3 test_p5_group2_legacy_status_candidate.py
python3 test_p5_group2_legacy_status_revocation.py
python3 test_p5_group3_admin_user_mgmt_candidate.py
python3 test_p5_group3_admin_user_mgmt_revocation.py
python3 test_p5_group4_safe_summary_candidate.py
node test_p5_group4_safe_summary_bff.mjs
python3 test_p5_group4_safe_summary_revocation.py
python3 test_p5_group5_session_state_candidate.py
node test_p5_group5_session_state_bff.mjs
python3 test_p5_group5_session_state_revocation.py
python3 test_p5_group6_public_boundary_candidate.py
node test_p5_group6_public_boundary_bff.mjs
python3 test_p5_group6_public_boundary_revocation.py
python3 test_post_p5_audit_sequence_acl.py
python3 test_post_p5_service_role_rpc_minimization.py
python3 test_post_p5_service_role_relation_acl.py
node test_post_p5_login_trusted_source_bucket.mjs
python3 test_post_p5_login_trusted_source_bucket.py
python3 test_post_p5_crm_acl_event_guard.py
python3 test_post_p5_crm_rls_alter_guard.py
node --check dist/cloud-adapter.js
node --check dist/cloud-security-hotfix.js
node --check dist/cloud-ui-action-bridge.js
