from pathlib import Path
import hashlib
import re

ROOT = Path(__file__).resolve().parent
APP_DIR = ROOT / 'dist' / 'app'


def fail(message: str) -> None:
    raise SystemExit('DESTRUCTIVE_CONFIRMATION_INTEGRITY_FINALIZE_FAILED: ' + message)


def method_bounds(text: str, name: str):
    signature = re.compile(rf'(?:^|[,\n])\s*({re.escape(name)}\([^)]*\)\s*\{{)', re.M)
    match = signature.search(text)
    if not match:
        return None
    start = match.start() + match.group(0).index(match.group(1))
    tail = text[start:]
    defs = list(re.finditer(r'(?:^|[,]\s*|\n\s*)([A-Za-z_$][A-Za-z0-9_$]*)\s*\([^)]*\)\s*\{', tail))
    if len(defs) < 2 or defs[0].group(1) != name:
        fail(f'{name} boundary parser drifted')
    end = start + defs[1].start() + defs[1].group(0).index(defs[1].group(1))
    return start, end


REPLACEMENTS = {
    'deleteFinanceCost': """deleteFinanceCost(cost){const resolve=()=>Array.isArray(this.financeCosts)?this.financeCosts.find(c=>String(c?.id)===String(cost?.id)):cost;let target=resolve();if(!target){this.notify('成本记录状态已变化，请重新操作');return}const denyAuto=c=>{if(!c?.autoGenerated)return false;this.notify(c.sourceType==='OPENING_DEAL'?'自动开户成本不能单独删除，请修改对应开户渠道':c.sourceType==='RECEIVABLE_ITEM'?'收入项目联动成本不能单独删除，请修改对应收入项目':'自动 IP / 网络成本不能单独删除，请修改客户网络环境');return true};if(denyAuto(target))return;if(!this.assertMonthUnlocked(String(target.date||'').slice(0,7),'删除成本'))return;this.askConfirm({title:'删除成本记录',message:`确定删除 ${target.date||''} 的【${this.financeCostCategoryText(target.category)} · ${this.formatMoney(target.amount,target.currency)}】吗？`,confirmText:'确认删除'},()=>{target=resolve();if(!target){this.notify('成本记录状态已变化，请重新操作');return}if(denyAuto(target))return;if(!this.assertMonthUnlocked(String(target.date||'').slice(0,7),'删除成本'))return;this.financeCosts=this.financeCosts.filter(c=>String(c?.id)!==String(target.id));this.persist();this.logAudit('删除成本',`${this.financeCostCategoryText(target.category)} · ${this.formatMoney(target.amount,target.currency)}`);this.notify('成本记录已删除，净利润已重新计算')})},""",
    'deleteReceivablePayment': """deleteReceivablePayment(r,pay){const resolveTarget=()=>Array.isArray(this.financeReceivables)?this.financeReceivables.find(x=>String(x?.id)===String(r?.id)):r,resolvePay=target=>(target?.payments||[]).find(p=>String(p?.id)===String(pay?.id));let target=resolveTarget(),livePay=resolvePay(target);if(!target||!livePay){if(r&&pay)this.notify('回款流水状态已变化，请重新操作');return}if(!this.assertMonthUnlocked(String(livePay.date||'').slice(0,7),'删除该到账月份的回款'))return;this.askConfirm({title:'删除回款流水',message:`确定删除 ${livePay.date} 的回款 ${this.formatMoney(livePay.amount,target.currency)} 吗？删除后已收与未收金额会自动重新计算。`,confirmText:'确认删除'},()=>{target=resolveTarget();livePay=resolvePay(target);if(!target||!livePay){this.notify('回款流水状态已变化，请重新操作');return}if(!this.assertMonthUnlocked(String(livePay.date||'').slice(0,7),'删除该到账月份的回款'))return;target.payments=(target.payments||[]).filter(p=>String(p?.id)!==String(livePay.id));target.paidAmount=this.financeReceivablePaid(target);if(String(this.receivableForm?.id)===String(target.id))this.receivableForm=this.normalizeReceivable(target);this.persist();this.logAudit('删除回款流水',`${this.financeReceivableClientName(target)} · ${livePay.date} · ${this.formatMoney(livePay.amount,target.currency)}`);this.notify('回款流水已删除')})},""",
    'deleteReceivable': """deleteReceivable(r){const resolve=()=>Array.isArray(this.financeReceivables)?this.financeReceivables.find(x=>String(x?.id)===String(r?.id)):r,eligible=target=>{if(!target){this.notify('收入项目状态已变化，请重新操作');return false}if(!this.assertMonthUnlocked(target.settlementMonth,'删除收入项目'))return false;if(this.financeReceivablePaid(target)>0){this.notify('该收入项目已有回款流水，不能直接删除。请保留记录或先删除回款流水。');return false}const linked=this.receivableLinkedCost(target);if(linked&&this.isMonthLocked(String(linked.date||'').slice(0,7))){this.notify('关联项目成本所在月份已月结，不能删除该收入项目');return false}return true};let target=resolve();if(!eligible(target))return;this.askConfirm({title:'删除收入项目',message:`确定删除【${this.financeReceivableClientName(target)} · ${this.financeIncomeTypeText(target.incomeType)} · ${target.projectName||target.settlementMonth}】吗？关联的项目直接成本会同步删除。`,confirmText:'确认删除'},()=>{target=resolve();if(!eligible(target))return;this.financeReceivables=this.financeReceivables.filter(x=>String(x?.id)!==String(target.id));this.financeCosts=this.financeCosts.filter(c=>!(c.sourceType==='RECEIVABLE_ITEM'&&String(c.sourceId)===String(target.id)));this.persist();this.logAudit('删除收入项目',`${this.financeReceivableClientName(target)} · ${target.settlementMonth} · ${this.financeIncomeTypeText(target.incomeType)}`);this.notify('收入项目及关联成本已删除，净利润已重新计算')})},""",
    'archiveClient': """archiveClient(client){const resolve=()=>Array.isArray(this.clients)?this.clients.find(c=>String(c?.id)===String(client?.id)):client;let target=resolve();if(!target||target.archived)return;if(!this.canArchiveClients()){this.notify('当前角色没有归档客户的权限');return}this.askConfirm({title:'归档客户',message:`确定归档客户【${target.name}】吗？\n\n归档后历史广告、开户、财务和回款数据都会保留，但客户不再参与当前运营预警。`,confirmText:'确认归档',tone:'warning'},()=>{if(!this.canArchiveClients()){this.notify('当前角色没有归档客户的权限');return}target=resolve();if(!target||target.archived){this.notify('客户状态已变化，请重新操作');return}target.archived=true;target.archivedAt=new Date().toISOString();target.status='PAUSED';this.persist();this.logAudit('归档客户',target.name);this.notify(`客户【${target.name}】已归档`)})},""",
    'restoreClient': """restoreClient(client){const resolve=()=>Array.isArray(this.clients)?this.clients.find(c=>String(c?.id)===String(client?.id)):client;let target=resolve();if(!target?.archived)return;if(!this.canArchiveClients()){this.notify('当前角色没有恢复客户的权限');return}this.askConfirm({title:'恢复归档客户',message:`确定恢复客户【${target.name}】吗？`,confirmText:'确认恢复',tone:'warning'},()=>{if(!this.canArchiveClients()){this.notify('当前角色没有恢复客户的权限');return}target=resolve();if(!target?.archived){this.notify('客户状态已变化，请重新操作');return}target.archived=false;target.archivedAt='';target.status='ACTIVE';this.persist();this.logAudit('恢复归档客户',target.name);this.notify('客户已恢复到当前合作客户')})},""",
    'deleteLead': """deleteLead(lead){const resolve=()=>Array.isArray(this.leads)?this.leads.find(l=>String(l?.id)===String(lead?.id)):lead;let target=resolve();if(!target)return;this.askConfirm({title:'删除潜在客户',message:`确定删除潜在客户【${target.company}】吗？\n该线索的联系人、报价、跟进阶段和备注都会一并删除。`,confirmText:'确认删除'},()=>{target=resolve();if(!target){this.notify('潜在客户状态已变化，请重新操作');return}this.leads=this.leads.filter(l=>String(l?.id)!==String(target.id));this.persist();this.logAudit('删除潜在客户',target.company);this.notify(`潜在客户【${target.company}】已删除`)})},""",
    'toggleFinanceMonthLock': """toggleFinanceMonthLock(monthKey){if(!monthKey)return;if(!this.canManageFinance()){this.notify('当前角色无财务月结权限');return}const locked=this.isMonthLocked(monthKey);if(locked&&this.currentUser?.role!=='ADMIN'){this.notify('只有管理员可以解除已完成的月结锁定');return}if(locked){this.askConfirm({title:'解除财务月结',message:`确定解除 ${monthKey} 的月结锁定吗？解除后该月广告、渠道返点、应收金额和成本将重新允许修改，月结冻结快照也会失效。`,confirmText:'确认解锁',tone:'warning'},()=>{if(!this.canManageFinance()){this.notify('当前角色无财务月结权限');return}if(this.currentUser?.role!=='ADMIN'){this.notify('只有管理员可以解除已完成的月结锁定');return}if(!this.isMonthLocked(monthKey)){this.notify('月结状态已变化，请重新操作');return}delete this.financeMonthLocks[monthKey];delete this.financeMonthSnapshots[monthKey];this.persist();this.logAudit('解除财务月结',monthKey);this.notify(`${monthKey} 已解锁`)})}else{this.ensureAutomaticReceivables({silent:true});this.ensureAutomaticAssetCosts({month:monthKey,silent:true});const check=this.runFinanceMonthCheck(monthKey,false);if(check.issues.length){this.notify(`月结检查未通过：${check.issues.join('；')}`);return}this.askConfirm({title:'完成财务月结',message:`${monthKey} 月结检查已通过。确定完成月结吗？系统会冻结该月收入、广告消耗、返点、成本与利润口径；以后仍可按实际到账日期登记跨月回款。`,confirmText:'确认月结',tone:'warning'},()=>{if(!this.canManageFinance()){this.notify('当前角色无财务月结权限');return}if(this.isMonthLocked(monthKey)){this.notify('月结状态已变化，请重新操作');return}const liveCheck=this.getFinanceMonthCheck(monthKey);if(liveCheck.issues.length){this.notify(`月结检查未通过：${liveCheck.issues.join('；')}`);return}const snapshot=this.buildFinanceMonthSnapshot(monthKey);this.financeMonthSnapshots[monthKey]=snapshot;this.financeMonthLocks[monthKey]={lockedAt:new Date().toISOString(),lockedBy:this.currentUser?.name||'',snapshotAt:snapshot.createdAt};this.persist();this.logAudit('完成财务月结',`${monthKey} · 已生成冻结快照`);this.notify(`${monthKey} 已完成月结，历史利润口径已冻结`)})}},""",
    'voidReconciliation': """voidReconciliation(row){const initial=row?.record,resolve=()=>Array.isArray(this.financeReconciliations)?this.financeReconciliations.find(r=>String(r?.id)===String(initial?.id)):initial;let rec=resolve();if(!rec||rec.status==='VOID')return;if(!this.assertMonthUnlocked(rec.settlementMonth,'撤销返点对账'))return;this.askConfirm({title:'撤销返点对账',message:`确定撤销 ${row.providerName} / ${row.contactName} · ${rec.settlementMonth} 的返点对账吗？实际返点将从财务利润中移除。`,confirmText:'确认撤销',tone:'warning'},()=>{rec=resolve();if(!rec||rec.status==='VOID'){this.notify('对账状态已变化，请重新操作');return}if(!this.assertMonthUnlocked(rec.settlementMonth,'撤销返点对账'))return;rec.status='VOID';rec.voidedAt=new Date().toISOString();rec.voidedBy=this.currentUser?.name||'';this.financeActualRebates=this.financeActualRebates.filter(r=>!(String(r.providerId)===String(rec.providerId)&&String(r.contactId)===String(rec.contactId)&&r.settlementMonth===rec.settlementMonth&&(r.currency||'USD')===(rec.currency||'USD')));this.persist();this.logAudit('撤销代理商返点对账',`${row.providerName} / ${row.contactName} · ${rec.settlementMonth}`);this.notify('返点对账已撤销，实际返点与利润已重新计算')})},""",
}

REQUIRED = {
    'deleteFinanceCost': ("title:'删除成本记录'", "this.assertMonthUnlocked(String(cost.date||'').slice(0,7),'删除成本')", "this.financeCosts=this.financeCosts.filter(c=>c.id!==cost.id)"),
    'deleteReceivablePayment': ("title:'删除回款流水'", "const target=this.financeReceivables.find(x=>x.id===r?.id)||r", "target.payments=(target.payments||[]).filter(p=>p.id!==pay.id)"),
    'deleteReceivable': ("title:'删除收入项目'", "this.financeReceivablePaid(r)>0", "this.financeReceivables=this.financeReceivables.filter"),
    'archiveClient': ("title:'归档客户'", "this.canArchiveClients()", "client.archived=true"),
    'restoreClient': ("title:'恢复归档客户'", "this.canArchiveClients()", "client.archived=false"),
    'deleteLead': ("title:'删除潜在客户'", "this.leads=this.leads.filter", "this.logAudit('删除潜在客户'"),
    'toggleFinanceMonthLock': ("title:'解除财务月结'", "title:'完成财务月结'", "delete this.financeMonthLocks[monthKey]"),
    'voidReconciliation': ("title:'撤销返点对账'", "this.assertMonthUnlocked(rec.settlementMonth,'撤销返点对账')", "rec.status='VOID'"),
}

if not APP_DIR.is_dir():
    fail('dist/app missing')
files = sorted(APP_DIR.glob('app-inline-*.js'))
if not files:
    fail('no final app-inline JS artifacts')

counts = {name: 0 for name in REPLACEMENTS}
changed = []
for path in files:
    text = path.read_text(encoding='utf-8')
    original = text
    for name, replacement in REPLACEMENTS.items():
        bounds = method_bounds(text, name)
        if bounds is None:
            continue
        counts[name] += 1
        start, end = bounds
        source = text[start:end]
        missing = [marker for marker in REQUIRED[name] if marker not in source]
        if missing:
            fail(f'{name} reviewed source drifted: ' + ', '.join(missing))
        text = text[:start] + replacement + text[end:]
    if text != original:
        path.write_text(text, encoding='utf-8')
        changed.append((path.name, hashlib.sha256(text.encode('utf-8')).hexdigest()))

bad_counts = [f'{name}={count}' for name, count in counts.items() if count != 1]
if bad_counts:
    fail('expected each method exactly once: ' + ', '.join(bad_counts))
if len(changed) != 1:
    fail(f'expected exactly one changed app artifact, found {len(changed)}')

print(
    'DESTRUCTIVE_CONFIRMATION_INTEGRITY_FINALIZE_OK: '
    'finance-cost=live-target+auto+lock-recheck; '
    'payment=live-receivable+live-payment+lock-recheck; '
    'receivable=live-target+payment+linked-lock-recheck; '
    'client-lifecycle=permission+live-state-recheck; lead-delete=live-id-recheck; '
    'month-lock=permission+role+state+check-revalidation; reconciliation=live-status+lock-recheck; '
    f'artifact={changed[0][0]}:{changed[0][1][:12]}'
)
