import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=process.cwd();
const appDir=path.join(root,'dist','app');
const adapterPath=path.join(root,'dist','cloud-adapter.js');
if(!fs.existsSync(appDir)||!fs.existsSync(adapterPath))throw new Error('BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_FAILED: final artifacts missing');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort();
const bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n');

function extract(name){
  const signature=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m');
  const match=signature.exec(bundle);
  if(!match)throw new Error(`BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_FAILED: ${name} missing`);
  const start=match.index+match[0].indexOf(match[1]),tail=bundle.slice(start);
  const defs=[...tail.matchAll(/(?:^|[,]\s*|\n\s*)([A-Za-z_$][A-Za-z0-9_$]*)\s*\([^)]*\)\s*\{/g)];
  if(defs.length<2||defs[0][1]!==name)throw new Error(`BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_FAILED: ${name} parser drifted`);
  const next=defs[1].index+defs[1][0].indexOf(defs[1][1]);
  return tail.slice(0,next).replace(/,\s*$/,'').trim();
}

let methods;
try{methods=vm.runInNewContext(`({${['saveReceivable','deleteReceivable'].map(extract).join(',')}})`,{Date,Math,Number,String,Object,Array,JSON,Set,Promise},{timeout:1000})}
catch(error){throw new Error(`BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_FAILED: final methods not executable: ${error.message}`)}

const adapter=fs.readFileSync(adapterPath,'utf8');
const bootAnchor='\n  boot();\n})();';
if(adapter.split(bootAnchor).length!==2)throw new Error('BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_FAILED: adapter boot anchor drifted');
const harnessAdapter=adapter.replace(bootAnchor,'\n})();');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const findings=[];
function response(status){return {ok:status>=200&&status<300,status,json:async()=>status>=200&&status<300?({revision:status}):({message:'SYNTHETIC_RECEIVABLE_SAVE_FAILED'})}}
function parseState(call){const body=JSON.parse(call?.body||'{}');if(body.rpc!=='crm_save_state')throw new Error(`BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_FAILED: unexpected rpc=${body.rpc}`);return body.args?.p_state}

function makeRuntime(kind){
  const calls={fetch:[],notify:[]};
  const subject={};
  let saveAttempt=0,confirmAction=null,auditId=0,uid=0;
  const localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
  const window={__growthOpsVm:subject,location:{hash:'#finance'}};
  const document={documentElement:{classList:{remove:()=>{},add:()=>{}}},body:{appendChild:()=>{}},createElement:()=>({click(){},remove(){}})};
  const fetchMock=async(url,options={})=>{calls.fetch.push({url:String(url),body:String(options.body||'')});saveAttempt+=1;return response(saveAttempt===1?503:200)};
  vm.runInNewContext(harnessAdapter,{window,document,localStorage,URL:{createObjectURL:()=>'',revokeObjectURL:()=>{}},FileReader:class{},Blob,TextEncoder,structuredClone,crypto,console,setTimeout,clearTimeout,Date,Math,JSON,String,Number,Object,Array,Promise,Error,fetch:fetchMock},{timeout:1000});

  const row=kind==='create'?null:{id:'recv-1',ownerType:'CLIENT',clientId:'c1',payerName:'',settlementMonth:'2026-09',incomeType:'OTHER',projectName:'Original',currency:'USD',amount:100,directCost:20,directCostDate:'2026-09-01',costVendor:'Vendor A',dueDate:'2026-09-30',invoiceStatus:'PENDING',invoiceNo:'',note:'original',payments:[],paidAmount:0,billSource:'MANUAL'};
  const cost=row?{id:'cost-1',date:'2026-09-01',category:'OTHER',scope:'CLIENT',clientId:'c1',currency:'USD',amount:20,vendor:'Vendor A',sourceType:'RECEIVABLE_ITEM',sourceId:'recv-1',autoGenerated:true}:null;
  const form=kind==='create'
    ?{id:null,ownerType:'CLIENT',clientId:'c1',payerName:'',settlementMonth:'2026-09',incomeType:'OTHER',projectName:'New Revenue',currency:'USD',amount:'120',directCost:'30',directCostDate:'2026-09-01',costVendor:'Vendor New',collectionMode:'RECEIVABLE',receivedDate:'2026-09-04',paymentMethod:'银行转账',paymentAccount:'',dueDate:'2026-09-30',invoiceStatus:'PENDING',invoiceNo:'',note:'new',payments:[],billSource:'MANUAL'}
    :{...structuredClone(row),projectName:'Edited Revenue',amount:'150',directCost:'35',costVendor:'Vendor Edited'};

  Object.assign(subject,methods,{
    currentUser:{id:'finance',name:'Finance User',role:'FINANCE',enabled:true},clients:[{id:'c1',name:'Alpha',archived:false}],
    financeReceivables:row?[row]:[],financeCosts:cost?[cost]:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],backupSnapshots:[],auditLogs:[],
    receivableForm:form,showReceivableModal:true,
    assertMonthUnlocked:()=>true,isMonthLocked:()=>false,localDateKey:()=> '2026-09-04',accountUid:prefix=>`${prefix}-${++uid}`,
    normalizeReceivable:r=>{const x=structuredClone(r||{});x.payments=Array.isArray(x.payments)?x.payments:[];x.amount=Number(x.amount||0);x.directCost=Number(x.directCost||0);x.paidAmount=x.payments.reduce((s,p)=>s+Number(p.amount||0),0);return x},
    normalizeFinanceCost:c=>structuredClone(c),financeReceivablePaid:r=>(r?.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0),
    receivableLinkedCost:r=>subject.financeCosts.find(c=>c.sourceType==='RECEIVABLE_ITEM'&&String(c.sourceId)===String(r?.id))||null,
    syncReceivableLinkedCost:r=>{const existing=subject.financeCosts.find(c=>c.sourceType==='RECEIVABLE_ITEM'&&String(c.sourceId)===String(r?.id));if(Number(r?.directCost||0)<=0){if(existing)subject.financeCosts=subject.financeCosts.filter(c=>c!==existing);return existing?1:0}const payload={id:existing?.id||`cost-${++uid}`,date:r.directCostDate||`${r.settlementMonth}-01`,category:'OTHER',scope:'CLIENT',clientId:String(r.clientId||''),currency:r.currency||'USD',amount:Number(r.directCost||0),vendor:r.costVendor||'',sourceType:'RECEIVABLE_ITEM',sourceId:String(r.id),autoGenerated:true};if(existing)Object.assign(existing,payload);else subject.financeCosts.unshift(payload);return 1},
    financeReceivableClientName:()=> 'Alpha',financeIncomeTypeText:()=> '其他收入',financeReceivableMargin:r=>Number(r?.amount||0)-Number(r?.directCost||0),formatMoney:(v,c)=>`${c||'USD'}:${Number(v)}`,
    askConfirm:(_config,action)=>{confirmAction=action},
    logAudit:(action,target)=>{const audit={id:`audit-${++auditId}`,action:String(action),target:String(target)};subject.auditLogs.push(audit);return audit},
    notify:message=>calls.notify.push(String(message)),ensureDailyBackup:()=>{},
    collectBackupPayload:()=>({clients:structuredClone(subject.clients),financeReceivables:structuredClone(subject.financeReceivables),financeCosts:structuredClone(subject.financeCosts),financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],auditLogs:structuredClone(subject.auditLogs),backupSnapshots:[]}),
  });
  return {subject,row,cost,calls,getConfirm:()=>confirmAction};
}

async function settleFirstFailure(calls){await sleep(260);if(calls.fetch.length<1)throw new Error('BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_FAILED: expected first cloud save attempt')}
async function laterPersist(subject,calls){subject.persist();await sleep(260);if(calls.fetch.length<2)throw new Error('BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_FAILED: expected later cloud save attempt');return parseState(calls.fetch.at(-1))}

// CREATE: current shipped code closes/succeeds before the cloud acknowledgement, then
// leaves the new receivable, linked cost and audit in memory after the 503.
{
  const {subject,calls}=makeRuntime('create');subject.saveReceivable();
  if(subject.showReceivableModal===false||calls.notify.some(m=>m.includes('收入项目已保存')))findings.push('saveReceivable create announces/closes before durable ACK');
  await settleFirstFailure(calls);
  const created=subject.financeReceivables.find(r=>r.projectName==='New Revenue');
  if(created&&subject.financeCosts.some(c=>String(c.sourceId)===String(created.id))&&subject.auditLogs.some(a=>a.action==='新增收入项目'))findings.push('saveReceivable create 503 leaves false receivable/cost/audit in memory');
  const later=await laterPersist(subject,calls);
  const laterRow=later.financeReceivables.find(r=>r.projectName==='New Revenue');
  if(laterRow&&later.financeCosts.some(c=>String(c.sourceId)===String(laterRow.id))&&later.auditLogs.some(a=>a.action==='新增收入项目'))findings.push('saveReceivable create later persist resurrects failed create');
}

// EDIT: failed persistence must not leave an edited accounting basis that a later save
// can make durable.
{
  const {subject,calls}=makeRuntime('edit');subject.saveReceivable();
  if(subject.showReceivableModal===false||calls.notify.some(m=>m.includes('收入项目已保存')))findings.push('saveReceivable edit announces/closes before durable ACK');
  await settleFirstFailure(calls);
  const edited=subject.financeReceivables.find(r=>r.id==='recv-1'),editedCost=subject.financeCosts.find(c=>c.sourceId==='recv-1');
  if(edited?.amount===150&&editedCost?.amount===35&&subject.auditLogs.some(a=>a.action==='修改收入项目'))findings.push('saveReceivable edit 503 leaves edited receivable/cost/audit in memory');
  const later=await laterPersist(subject,calls),laterRow=later.financeReceivables.find(r=>r.id==='recv-1'),laterCost=later.financeCosts.find(c=>c.sourceId==='recv-1');
  if(laterRow?.amount===150&&laterCost?.amount===35&&later.auditLogs.some(a=>a.action==='修改收入项目'))findings.push('saveReceivable edit later persist makes failed edit durable');
}

// DELETE: destructive confirmation is already live-target/month-lock hardened, but the
// confirmed deletion itself is still optimistic relative to durable cloud state.
{
  const {subject,row,calls,getConfirm}=makeRuntime('delete');subject.deleteReceivable(row);const confirm=getConfirm();if(typeof confirm!=='function')throw new Error('BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_FAILED: delete confirmation missing');confirm();
  if(calls.notify.some(m=>m.includes('已删除')))findings.push('deleteReceivable announces success before durable ACK');
  await settleFirstFailure(calls);
  if(!subject.financeReceivables.some(r=>r.id==='recv-1')&&!subject.financeCosts.some(c=>c.sourceId==='recv-1')&&subject.auditLogs.some(a=>a.action==='删除收入项目'))findings.push('deleteReceivable 503 leaves false deletion/audit in memory');
  const later=await laterPersist(subject,calls);
  if(!later.financeReceivables.some(r=>r.id==='recv-1')&&!later.financeCosts.some(c=>c.sourceId==='recv-1')&&later.auditLogs.some(a=>a.action==='删除收入项目'))findings.push('deleteReceivable later persist makes failed deletion durable');
}

if(findings.length){throw new Error(`BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_FINDINGS: count=${findings.length}; ${findings.join(' | ')}`)}
console.log('BUSINESS_RECEIVABLE_PERSISTENCE_ACK_PROBE_SAFE: create+edit+delete=durable-ack-safe');
