import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=process.cwd();
const appDir=path.join(root,'dist','app');
const adapterPath=path.join(root,'dist','cloud-adapter.js');
if(!fs.existsSync(appDir)||!fs.existsSync(adapterPath))throw new Error('BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_FAILED: final artifacts missing');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort();
const bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n');

function extractMethod(name){
  const signature=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m');
  const match=signature.exec(bundle);
  if(!match)throw new Error(`BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_FAILED: ${name} missing`);
  const start=match.index+match[0].indexOf(match[1]);
  const open=bundle.indexOf('{',start);
  let depth=0,quote='',escaped=false,lineComment=false,blockComment=false;
  for(let i=open;i<bundle.length;i+=1){
    const ch=bundle[i],next=bundle[i+1]||'';
    if(lineComment){if(ch==='\n')lineComment=false;continue}
    if(blockComment){if(ch==='*'&&next==='/'){blockComment=false;i+=1}continue}
    if(quote){if(escaped){escaped=false;continue}if(ch==='\\'){escaped=true;continue}if(ch===quote)quote='';continue}
    if(ch==='/'&&next==='/'){lineComment=true;i+=1;continue}
    if(ch==='/'&&next==='*'){blockComment=true;i+=1;continue}
    if(ch==='"'||ch==="'"||ch==='`'){quote=ch;continue}
    if(ch==='{')depth+=1;
    else if(ch==='}'){depth-=1;if(depth===0)return bundle.slice(start,i+1).trim()}
  }
  throw new Error(`BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_FAILED: ${name} closing brace missing`);
}

let methods;
try{methods=vm.runInNewContext(`({${['saveOpeningDeal','deleteOpeningDeal'].map(extractMethod).join(',')}})`,{Date,Math,Number,String,Object,Array,JSON,Set,Promise},{timeout:1000})}
catch(error){throw new Error(`BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_FAILED: final methods not executable: ${error.message}`)}

const adapter=fs.readFileSync(adapterPath,'utf8');
const bootAnchor='\n  boot();\n})();';
if(adapter.split(bootAnchor).length!==2)throw new Error('BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_FAILED: adapter boot anchor drifted');
const harnessAdapter=adapter.replace(bootAnchor,'\n})();');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const clone=value=>JSON.parse(JSON.stringify(value));
const fail=message=>{throw new Error('BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_FAILED: '+message)};
const ok=(value,label)=>{if(!value)fail(label)};
const eq=(actual,expected,label)=>{if(actual!==expected)fail(`${label}; expected=${expected}; actual=${actual}`)};
function deferred(){let resolve;const promise=new Promise(r=>{resolve=r});return {promise,resolve}}
function response(status){return {ok:status>=200&&status<300,status,json:async()=>status>=200&&status<300?({revision:status}):({message:'SYNTHETIC_OPENING_DEAL_SAVE_FAILED'})}}
function parseState(call){const body=JSON.parse(call?.body||'{}');if(body.rpc!=='crm_save_state')fail(`unexpected rpc=${body.rpc}`);return body.args?.p_state||{}}

const validForm=(overrides={})=>({id:null,clientId:'client-1',externalClientName:'',providerId:'provider-1',contactId:'',partnerName:'',contactName:'',status:'OPENED',effectiveStartDate:'2026-09-01',effectiveEndDate:'',submitDate:'2026-08-20',expectedDate:'2026-09-01',platform:'FB',accountType:'广告账户',adAccountIds:'',quantity:1,fee:100,currency:'USD',notes:'',...overrides});
const deal=(overrides={})=>({...validForm({id:'deal-1'}),...overrides});
const linkedCost=(overrides={})=>({id:'cost-opening-1',date:'2026-09-01',sourceType:'OPENING_DEAL',sourceId:'deal-1',autoGenerated:true,amount:100,currency:'USD',clientId:'client-1',...overrides});

function makeRuntime({kind,first='fail',withBarrier=true}){
  const calls={fetch:[],notify:[]};
  const subject={};let saveAttempt=0,confirmAction=null,auditId=0,uid=0;
  const gate=first==='deferred'?deferred():null;
  const localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
  const window={__growthOpsVm:subject,location:{hash:'#account-opening'}};
  const document={documentElement:{classList:{remove:()=>{},add:()=>{}}},body:{appendChild:()=>{}},createElement:()=>({click(){},remove(){}})};
  const fetchMock=async(url,options={})=>{
    calls.fetch.push({url:String(url),body:String(options.body||'')});saveAttempt+=1;
    if(saveAttempt===1){if(first==='fail')return response(503);if(first==='deferred')return gate.promise;}
    return response(200);
  };
  vm.runInNewContext(harnessAdapter,{window,document,localStorage,URL:{createObjectURL:()=>'',revokeObjectURL:()=>{}},FileReader:class{},Blob,TextEncoder,structuredClone,crypto,console,setTimeout,clearTimeout,Date,Math,JSON,String,Number,Object,Array,Promise,Error,fetch:fetchMock},{timeout:1000});
  if(!withBarrier)delete subject.persistOpeningDealBarrier;
  const existing=kind==='create'?null:deal();
  Object.assign(subject,methods,{
    currentUser:{id:'finance',name:'Finance User',role:'FINANCE',enabled:true},clients:[],openingProviders:[],openingDeals:existing?[clone(existing)]:[],financeCosts:existing?[linkedCost()]:[],auditLogs:[],backupSnapshots:[],financeReceivables:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],
    openingForm:kind==='create'?validForm():validForm({id:'deal-1',fee:220,currency:'CNY'}),showOpeningModal:true,
    openingProvider:()=>({id:'provider-1',name:'Provider A',contacts:[]}),openingProviderContacts:()=>[],openingContact:()=>null,openingDealUnmatchedIds:()=>[],openingDealMatchedAccounts:()=>[],accountRebateMode:()=> 'CHANNEL',
    localDateKey:()=> '2026-09-02',accountUid:prefix=>`${prefix}-${++uid}`,openingClientName:()=> 'Client A',openingProviderName:()=> 'Provider A',openingContactName:()=> 'Contact A',isMonthLocked:()=>false,
    syncOpeningFeeCost:payload=>{const id=String(payload.id);const idx=subject.financeCosts.findIndex(c=>c.sourceType==='OPENING_DEAL'&&String(c.sourceId)===id);const row={id:idx>-1?subject.financeCosts[idx].id:`cost-${id}`,date:String(payload.effectiveStartDate||payload.expectedDate||'2026-09-01'),sourceType:'OPENING_DEAL',sourceId:id,autoGenerated:true,amount:Number(payload.fee||0),currency:payload.currency||'USD',clientId:payload.clientId||''};if(idx>-1)subject.financeCosts.splice(idx,1,row);else subject.financeCosts.push(row);return 1},
    askConfirm:(_cfg,action)=>{confirmAction=action},logAudit:(action,target)=>{const row={id:`audit-${++auditId}`,action:String(action),target:String(target)};subject.auditLogs.push(row);return row},notify:m=>calls.notify.push(String(m)),ensureDailyBackup:()=>{},
    collectBackupPayload:()=>({clients:[],openingProviders:[],openingDeals:clone(subject.openingDeals),financeCosts:clone(subject.financeCosts),auditLogs:clone(subject.auditLogs),backupSnapshots:[],financeReceivables:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[]}),
  });
  return {subject,existing,calls,getConfirm:()=>confirmAction,resolveFirst:status=>gate?.resolve(response(status))};
}

async function persistedRollback(calls){await sleep(240);ok(calls.fetch.length>=2,'rollback must itself reach serialized save queue');return parseState(calls.fetch.at(-1))}
async function laterPersist(subject,calls){subject.persist();await sleep(240);return parseState(calls.fetch.at(-1))}

// CREATE success is gated by the real adapter acknowledgement: tentative source/cost may
// exist for serialization, but the editor remains open and success notice stays hidden.
{
  const {subject,calls,resolveFirst}=makeRuntime({kind:'create',first:'deferred'});const task=subject.saveOpeningDeal();ok(task&&typeof task.then==='function','create must expose ACK promise');ok(subject.openingDeals.length===1,'create tentative source exists while pending');ok(subject.financeCosts.some(c=>c.sourceType==='OPENING_DEAL'),'create tentative linked cost exists while pending');ok(subject.showOpeningModal,'create editor remains open before ACK');eq(calls.notify.length,0,'create success notice held before ACK');resolveFirst(200);await task;eq(calls.fetch.length,1,'successful create uses one durable save');eq(subject.showOpeningModal,false,'create editor closes after ACK');ok(calls.notify.length>0,'create success notice emitted after ACK');
}

// CREATE failure removes only attempt state, persists rollback truth, and later saves
// cannot resurrect the failed source/cost/audit.
{
  const {subject,calls}=makeRuntime({kind:'create',first:'fail'});const task=subject.saveOpeningDeal();const attemptId=String(subject.openingDeals[0]?.id||'');ok(attemptId,'create attempt id allocated');await task;eq(subject.openingDeals.length,0,'failed create removes source');ok(!subject.financeCosts.some(c=>String(c.sourceId)===attemptId),'failed create removes linked cost');ok(!subject.auditLogs.some(a=>a.action==='新增客户开户渠道'),'failed create removes attempt audit');ok(subject.showOpeningModal,'failed create keeps editor open');ok(calls.notify.some(m=>m.includes('云端保存失败')),'failed create durable failure notice');const rollback=await persistedRollback(calls);eq((rollback.openingDeals||[]).length,0,'create rollback cloud excludes source');ok(!(rollback.financeCosts||[]).some(c=>String(c.sourceId)===attemptId),'create rollback cloud excludes linked cost');const later=await laterPersist(subject,calls);eq((later.openingDeals||[]).length,0,'later persist cannot resurrect failed create');
}

// EDIT success remains optimistic only in data while the editor/success UX waits for ACK.
{
  const {subject,calls,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'});const task=subject.saveOpeningDeal();eq(Number(subject.openingDeals[0]?.fee),220,'edit tentative source exists while pending');eq(Number(subject.financeCosts[0]?.amount),220,'edit tentative linked cost exists while pending');ok(subject.showOpeningModal,'edit editor remains open before ACK');eq(calls.notify.length,0,'edit success notice held');resolveFirst(200);await task;eq(calls.fetch.length,1,'successful edit uses one durable save');eq(subject.showOpeningModal,false,'edit editor closes after ACK');ok(calls.notify.length>0,'edit success notice after ACK');
}

// EDIT failure restores the exact original source and linked accounting basis and sends
// the restored truth through the serialized cloud queue.
{
  const {subject,calls}=makeRuntime({kind:'edit',first:'fail'});await subject.saveOpeningDeal();eq(Number(subject.openingDeals[0]?.fee),100,'failed edit restores source fee');eq(subject.openingDeals[0]?.currency,'USD','failed edit restores source currency');eq(Number(subject.financeCosts[0]?.amount),100,'failed edit restores linked cost amount');eq(subject.financeCosts[0]?.currency,'USD','failed edit restores linked cost currency');ok(!subject.auditLogs.some(a=>a.action==='修改客户开户渠道'),'failed edit removes attempt audit');const rollback=await persistedRollback(calls);eq(Number(rollback.openingDeals?.[0]?.fee),100,'edit rollback cloud restores source');eq(Number(rollback.financeCosts?.[0]?.amount),100,'edit rollback cloud restores linked cost');const later=await laterPersist(subject,calls);eq(Number(later.openingDeals?.[0]?.fee),100,'later persist cannot resurrect failed edit');eq(Number(later.financeCosts?.[0]?.amount),100,'later persist cannot resurrect failed linked cost');
}

// Failed EDIT rollback is attempt-scoped: unrelated concurrent rows/audits survive.
{
  const {subject,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'});const task=subject.saveOpeningDeal();const otherDeal=deal({id:'deal-other',fee:77}),otherCost=linkedCost({id:'cost-other',sourceId:'deal-other',amount:77}),otherAudit={id:'audit-other',action:'并发审计'};subject.openingDeals.push(otherDeal);subject.financeCosts.push(otherCost);subject.auditLogs.push(otherAudit);resolveFirst(503);await task;eq(Number(subject.openingDeals.find(d=>d.id==='deal-1')?.fee),100,'edit rollback restores target only');ok(subject.openingDeals.includes(otherDeal),'unrelated deal survives edit rollback');ok(subject.financeCosts.includes(otherCost),'unrelated cost survives edit rollback');ok(subject.auditLogs.includes(otherAudit),'unrelated audit survives edit rollback');
}

// Same-ID/source replacements written while the first save is pending are newer truth;
// stale rollback must not overwrite either replacement.
{
  const {subject,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'});const task=subject.saveOpeningDeal();const dealReplacement=deal({fee:888,currency:'EUR'}),costReplacement=linkedCost({amount:888,currency:'EUR'});subject.openingDeals.splice(0,1,dealReplacement);subject.financeCosts.splice(0,1,costReplacement);resolveFirst(503);await task;eq(subject.openingDeals.find(d=>d.id==='deal-1'),dealReplacement,'same-ID deal replacement authoritative');eq(subject.financeCosts.find(c=>c.sourceId==='deal-1'),costReplacement,'same-source linked cost replacement authoritative');
}

// DELETE success holds the positive notice until ACK, while the reversible local deletion
// supplies the state that the shared adapter must persist.
{
  const {subject,existing,calls,getConfirm,resolveFirst}=makeRuntime({kind:'delete',first:'deferred'});subject.deleteOpeningDeal(existing);const confirm=getConfirm();ok(typeof confirm==='function','delete confirmation missing');const task=confirm();ok(task&&typeof task.then==='function','delete callback exposes ACK promise');eq(subject.openingDeals.length,0,'delete source tentatively removed while pending');eq(subject.financeCosts.length,0,'delete linked cost tentatively removed while pending');eq(calls.notify.length,0,'delete success notice held before ACK');resolveFirst(200);await task;eq(calls.fetch.length,1,'successful delete uses one durable save');eq(subject.openingDeals.length,0,'successful delete source remains removed');eq(subject.financeCosts.length,0,'successful delete linked cost remains removed');ok(calls.notify.length>0,'delete success notice after ACK');
}

// DELETE failure restores source/cost and removes only the false attempt audit; rollback
// truth is persisted and a later save cannot commit the failed deletion.
{
  const {subject,existing,calls,getConfirm}=makeRuntime({kind:'delete',first:'fail'});subject.deleteOpeningDeal(existing);await getConfirm()();eq(subject.openingDeals.length,1,'failed delete restores source');eq(subject.financeCosts.length,1,'failed delete restores linked cost');ok(!subject.auditLogs.some(a=>a.action==='删除客户开户渠道'),'failed delete removes attempt audit');ok(calls.notify.some(m=>m.includes('云端保存失败')),'failed delete durable failure notice');const rollback=await persistedRollback(calls);eq((rollback.openingDeals||[]).length,1,'delete rollback cloud restores source');eq((rollback.financeCosts||[]).length,1,'delete rollback cloud restores linked cost');const later=await laterPersist(subject,calls);eq((later.openingDeals||[]).length,1,'later persist cannot commit failed deletion');eq((later.financeCosts||[]).length,1,'later persist cannot commit failed linked-cost deletion');
}

// DELETE rollback preserves unrelated live state and only restores the attempted pair.
{
  const {subject,existing,getConfirm,resolveFirst}=makeRuntime({kind:'delete',first:'deferred'});subject.deleteOpeningDeal(existing);const task=getConfirm()();const otherDeal=deal({id:'deal-other'}),otherCost=linkedCost({id:'cost-other',sourceId:'deal-other'}),otherAudit={id:'audit-delete-other',action:'并发审计'};subject.openingDeals.push(otherDeal);subject.financeCosts.push(otherCost);subject.auditLogs.push(otherAudit);resolveFirst(503);await task;ok(subject.openingDeals.some(d=>d.id==='deal-1'),'delete rollback restores target source');ok(subject.financeCosts.some(c=>c.sourceId==='deal-1'),'delete rollback restores target cost');ok(subject.openingDeals.includes(otherDeal),'delete rollback preserves unrelated deal');ok(subject.financeCosts.includes(otherCost),'delete rollback preserves unrelated cost');ok(subject.auditLogs.includes(otherAudit),'delete rollback preserves unrelated audit');
}

// Same-ID/source replacements after the tentative delete remain authoritative and unique.
{
  const {subject,existing,getConfirm,resolveFirst}=makeRuntime({kind:'delete',first:'deferred'});subject.deleteOpeningDeal(existing);const task=getConfirm()();const dealReplacement=deal({fee:999,currency:'EUR'}),costReplacement=linkedCost({amount:999,currency:'EUR'});subject.openingDeals.push(dealReplacement);subject.financeCosts.push(costReplacement);resolveFirst(503);await task;eq(subject.openingDeals.filter(d=>d.id==='deal-1').length,1,'delete same-ID replacement remains unique');eq(subject.financeCosts.filter(c=>c.sourceType==='OPENING_DEAL'&&c.sourceId==='deal-1').length,1,'delete same-source replacement remains unique');eq(subject.openingDeals.find(d=>d.id==='deal-1'),dealReplacement,'delete same-ID replacement authoritative');eq(subject.financeCosts.find(c=>c.sourceId==='deal-1'),costReplacement,'delete same-source replacement authoritative');
}

// Missing adapter helper fails closed for save and delete rather than falling back to the
// old debounced optimistic semantics.
{
  const {subject,calls}=makeRuntime({kind:'create',withBarrier:false});await subject.saveOpeningDeal();eq(subject.openingDeals.length,0,'missing create barrier rolls back source');eq(subject.financeCosts.length,0,'missing create barrier rolls back linked cost');ok(subject.showOpeningModal,'missing create barrier keeps editor open');ok(calls.notify.some(m=>m.includes('持久化服务不可用')),'missing create barrier fail-closed notice');
}
{
  const {subject,existing,calls,getConfirm}=makeRuntime({kind:'delete',withBarrier:false});subject.deleteOpeningDeal(existing);await getConfirm()();eq(subject.openingDeals.length,1,'missing delete barrier restores source');eq(subject.financeCosts.length,1,'missing delete barrier restores linked cost');ok(calls.notify.some(m=>m.includes('持久化服务不可用')),'missing delete barrier fail-closed notice');
}

console.log('BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_OK: authority=final-app+final-cloud-adapter; create+edit+delete=success-after-save-ack; failure=deal+linked-opening-cost+attempt-audit-rollback+rollback-persisted; later-persist=failed-operation-not-resurrected; concurrency=unrelated-state-preserved+same-id/source-replacement-authoritative; missing-barrier=fail-closed; provider-paths=unchanged');
