import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=process.cwd(),appDir=path.join(root,'dist','app'),adapterPath=path.join(root,'dist','cloud-adapter.js');
if(!fs.existsSync(appDir)||!fs.existsSync(adapterPath))throw new Error('BUSINESS_STANDALONE_ALERT_PERSISTENCE_ACK_FAILED: final artifacts missing');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort(),bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n'),adapter=fs.readFileSync(adapterPath,'utf8');
if(!adapter.includes('vm.persistStandaloneAlertBarrier=()=>flushSave();'))throw new Error('BUSINESS_STANDALONE_ALERT_PERSISTENCE_ACK_FAILED: barrier not wired to shared flushSave');

function extract(name){const m=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m').exec(bundle);if(!m)throw new Error(`BUSINESS_STANDALONE_ALERT_PERSISTENCE_ACK_FAILED: ${name} missing`);const start=m.index+m[0].indexOf(m[1]),open=bundle.indexOf('{',start);let depth=0,quote='',escaped=false,line=false,block=false;for(let i=open;i<bundle.length;i++){const ch=bundle[i],next=bundle[i+1]||'';if(line){if(ch==='\n')line=false;continue}if(block){if(ch==='*'&&next==='/'){block=false;i++}continue}if(quote){if(escaped)escaped=false;else if(ch==='\\')escaped=true;else if(ch===quote)quote='';continue}if(ch==='/'&&next==='/'){line=true;i++;continue}if(ch==='/'&&next==='*'){block=true;i++;continue}if(ch==='"'||ch==="'"||ch==='`'){quote=ch;continue}if(ch==='{')depth++;else if(ch==='}'&&--depth===0)return bundle.slice(start,i+1).trim()}throw new Error(`BUSINESS_STANDALONE_ALERT_PERSISTENCE_ACK_FAILED: ${name} boundary`)}
const methods=vm.runInNewContext(`({${extract('saveStandaloneAlert')}})`,{Date,Math,Number,String,Object,Array,JSON,Set,Promise,Error},{timeout:1000});
const clone=v=>JSON.parse(JSON.stringify(v)),fail=m=>{throw new Error('BUSINESS_STANDALONE_ALERT_PERSISTENCE_ACK_FAILED: '+m)},eq=(a,b,m)=>{if(a!==b)fail(`${m}; expected=${JSON.stringify(b)}; actual=${JSON.stringify(a)}`)},same=(a,b,m)=>{if(JSON.stringify(a)!==JSON.stringify(b))fail(`${m}; expected=${JSON.stringify(b)}; actual=${JSON.stringify(a)}`)},ok=(v,m)=>{if(!v)fail(m)};
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject}}
function make({barrier='deferred',form=null}={}){const gate=deferred(),calls={barrier:0,persist:0,audit:0,notify:[]},existing={id:'sa-existing',typeKey:'IP',clientName:'Existing',dueDate:'2026-10-20',cost:'',target:''},initialForm=form||{typeKey:'IP',clientName:'Client A',dueDate:'2026-12-31',cost:'100',target:'Environment A'},subject={...methods,reminderTypeOptions:[{key:'IP',name:'IP'}],newAlertForm:initialForm,standaloneAlerts:[existing],showAddAlertModal:true,auditLogs:[{id:'audit-existing'}],persist(){calls.persist++},persistStandaloneAlertBarrier(){calls.barrier++;if(barrier==='ok')return Promise.resolve(true);if(barrier==='fail')return Promise.reject(new Error('SYNTHETIC_STANDALONE_SAVE_FAILED'));return gate.promise},logAudit(action,detail){calls.audit++;const row={id:`audit-${calls.audit}`,action:String(action),detail:String(detail)};subject.auditLogs.push(row);return row},notify(message){calls.notify.push(String(message))}};return{subject,existing,initialForm,calls,gate}}

// Valid creation is tentative until ACK; success UI is held.
{const {subject,initialForm,calls,gate}=make(),task=subject.saveStandaloneAlert();ok(task&&typeof task.then==='function','save returns ACK promise');eq(calls.barrier,1,'barrier once');eq(calls.persist,0,'legacy persist suppressed');eq(subject.standaloneAlerts.length,2,'tentative row added');eq(subject.showAddAlertModal,true,'modal held before ACK');eq(subject.newAlertForm,initialForm,'form object restored while pending');eq(calls.notify.length,0,'success notice held');gate.resolve(true);await task;eq(subject.standaloneAlerts.length,2,'row survives ACK');eq(subject.showAddAlertModal,false,'modal closes after ACK');ok(subject.newAlertForm!==initialForm,'form reset object applied after ACK');same(subject.newAlertForm,{typeKey:'IP',clientName:'',dueDate:'',cost:'',target:''},'form reset after ACK');ok(calls.notify.some(m=>m.includes('独立提醒已添加')),'success notice after ACK');eq(calls.audit,1,'audit emitted once')}

// Failure removes only the attempted row/audit and persists rollback truth.
{const {subject,initialForm,existing,calls}=make({barrier:'fail'}),beforeAudits=clone(subject.auditLogs);await subject.saveStandaloneAlert();eq(subject.standaloneAlerts.length,1,'failed row removed');eq(subject.standaloneAlerts[0],existing,'existing row preserved');same(subject.auditLogs,beforeAudits,'attempt audit removed');eq(subject.showAddAlertModal,true,'failure keeps modal');eq(subject.newAlertForm,initialForm,'failure keeps original form object');same(subject.newAlertForm,{typeKey:'IP',clientName:'Client A',dueDate:'2026-12-31',cost:'100',target:'Environment A'},'failure keeps form values');eq(calls.persist,1,'failure persists rollback truth');ok(calls.notify.some(m=>m.includes('云端保存失败')),'failure notice')}

// Concurrent unrelated rows/audits and newer form edits remain authoritative on failure.
{const {subject,initialForm,calls,gate}=make(),task=subject.saveStandaloneAlert(),attempt=subject.standaloneAlerts[0],concurrent={id:'sa-concurrent',typeKey:'IP',clientName:'Concurrent',dueDate:'2027-01-01'},concurrentAudit={id:'audit-concurrent'};subject.standaloneAlerts.push(concurrent);subject.auditLogs.push(concurrentAudit);initialForm.clientName='Next Client';initialForm.dueDate='2027-02-01';gate.reject(new Error('SYNTHETIC_STANDALONE_SAVE_FAILED'));await task;ok(!subject.standaloneAlerts.includes(attempt),'attempt row removed');ok(subject.standaloneAlerts.includes(concurrent),'concurrent row preserved');ok(subject.auditLogs.includes(concurrentAudit),'concurrent audit preserved');eq(subject.newAlertForm,initialForm,'newer form object preserved');eq(subject.newAlertForm.clientName,'Next Client','newer form text preserved');eq(subject.showAddAlertModal,true,'newer-entry modal remains open');eq(calls.persist,1,'concurrent rollback persisted')}

// Same-id replacement wins over a failed old attempt.
{const {subject,gate}=make(),task=subject.saveStandaloneAlert(),attempt=subject.standaloneAlerts[0],replacement={...clone(attempt),clientName:'Authoritative replacement'};subject.standaloneAlerts[0]=replacement;gate.reject(new Error('SYNTHETIC_STANDALONE_SAVE_FAILED'));await task;eq(subject.standaloneAlerts[0],replacement,'same-id replacement preserved');eq(replacement.clientName,'Authoritative replacement','replacement fields untouched')}

// If the user starts the next entry while ACK is pending, successful ACK must not clear it.
{const {subject,initialForm,calls,gate}=make(),task=subject.saveStandaloneAlert();initialForm.clientName='Next Client';initialForm.target='Next Target';gate.resolve(true);await task;eq(subject.newAlertForm,initialForm,'new entry form preserved after previous ACK');eq(subject.newAlertForm.clientName,'Next Client','new entry client preserved');eq(subject.showAddAlertModal,true,'modal stays open for new entry');ok(calls.notify.some(m=>m.includes('独立提醒已添加')),'previous save still reports success')}

// Missing durability service fails closed and performs zero legacy/network writes.
{const {subject,initialForm,calls}=make(),beforeRows=clone(subject.standaloneAlerts),beforeAudits=clone(subject.auditLogs);delete subject.persistStandaloneAlertBarrier;const result=subject.saveStandaloneAlert();eq(result,undefined,'missing barrier returns synchronously');same(subject.standaloneAlerts,beforeRows,'missing barrier restores rows');same(subject.auditLogs,beforeAudits,'missing barrier restores audits');eq(subject.newAlertForm,initialForm,'missing barrier keeps form');eq(subject.showAddAlertModal,true,'missing barrier keeps modal');eq(calls.persist,0,'missing barrier zero persist');ok(calls.notify.some(m=>m.includes('持久化服务不可用')),'missing barrier notice')}

// Existing type/calendar validation remains before mutation and barrier.
{const {subject,calls}=make({form:{typeKey:'UNKNOWN',clientName:'X',dueDate:'2026-12-31',cost:'',target:''}});const before=clone(subject.standaloneAlerts);subject.saveStandaloneAlert();same(subject.standaloneAlerts,before,'invalid type no mutation');eq(calls.barrier,0,'invalid type no barrier');eq(calls.persist,0,'invalid type no persist');eq(calls.audit,0,'invalid type no audit')}
{const {subject,calls}=make({form:{typeKey:'IP',clientName:'X',dueDate:'2026-02-30',cost:'',target:''}});const before=clone(subject.standaloneAlerts);subject.saveStandaloneAlert();same(subject.standaloneAlerts,before,'invalid date no mutation');eq(calls.barrier,0,'invalid date no barrier');eq(calls.persist,0,'invalid date no persist');eq(calls.audit,0,'invalid date no audit');ok(calls.notify.some(m=>m.includes('有效的到期日期')),'invalid date notice preserved')}

console.log('BUSINESS_STANDALONE_ALERT_PERSISTENCE_ACK_OK: authority=final-app+shared-flushSave-barrier; create=success-after-ACK; failure=attempt-row+audit rollback+rollback-persisted; concurrency=unrelated-row+same-id-replacement+new-form authority preserved; modal/form success UI ACK-gated; missing-barrier=fail-closed');
