import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=process.cwd(),appDir=path.join(root,'dist','app'),adapterPath=path.join(root,'dist','cloud-adapter.js');
if(!fs.existsSync(appDir)||!fs.existsSync(adapterPath))throw new Error('BUSINESS_CLIENT_SAVE_PERSISTENCE_ACK_FAILED: final artifacts missing');
const files=fs.readdirSync(appDir).filter(n=>/^app-inline-\d+\.js$/.test(n)).sort(),bundle=files.map(n=>fs.readFileSync(path.join(appDir,n),'utf8')).join('\n');
function extractMethod(name){
  const match=new RegExp(`(?:^|[,\\n])\\s*((?:async\\s+)?${name}\\s*\\([^)]*\\)\\s*\\{)`,'m').exec(bundle);
  if(!match)throw new Error(`BUSINESS_CLIENT_SAVE_PERSISTENCE_ACK_FAILED: ${name} missing`);
  const start=match.index+match[0].indexOf(match[1]),open=bundle.indexOf('{',start);let depth=0,quote='',escaped=false,line=false,block=false;
  for(let i=open;i<bundle.length;i+=1){const ch=bundle[i],next=bundle[i+1]||'';if(line){if(ch==='\n')line=false;continue}if(block){if(ch==='*'&&next==='/'){block=false;i+=1}continue}if(quote){if(escaped){escaped=false;continue}if(ch==='\\'){escaped=true;continue}if(ch===quote)quote='';continue}if(ch==='/'&&next==='/'){line=true;i+=1;continue}if(ch==='/'&&next==='*'){block=true;i+=1;continue}if(ch==='"'||ch==="'"||ch==='`'){quote=ch;continue}if(ch==='{')depth+=1;else if(ch==='}'&&--depth===0)return bundle.slice(start,i+1).trim()}
  throw new Error(`BUSINESS_CLIENT_SAVE_PERSISTENCE_ACK_FAILED: ${name} closing brace missing`);
}
const external=new Set(['persist','persistClientSaveBarrier','logAudit','notify','navigateTo','ensureAutomaticAssetCosts','ensureAutomaticReceivables','ensureClientFirstReceivable']),pure=new Set(['localDateKey']),sources=new Map();
function collect(name){if(sources.has(name)||external.has(name)||pure.has(name))return;const source=extractMethod(name);sources.set(name,source);for(const m of source.matchAll(/\bthis\.([A-Za-z_$][A-Za-z0-9_$]*)\s*\(/g)){const child=m[1];if(child!==name&&!external.has(child)&&!pure.has(child))collect(child)}}
collect('saveClient');
const context={Date,Number,String,Object,Array,Math,JSON,Set,Map,Intl,RegExp,structuredClone:globalThis.structuredClone,crypto:globalThis.crypto,setTimeout,clearTimeout},methods={};
for(const [name,source] of sources){try{methods[name]=vm.runInNewContext(`({${source}})`,context,{timeout:1000})[name]}catch(e){throw new Error(`BUSINESS_CLIENT_SAVE_PERSISTENCE_ACK_FAILED: shipped ${name} not executable: ${e.message}`)}}
const adapter=fs.readFileSync(adapterPath,'utf8'),boot='\n  boot();\n})();';if(adapter.split(boot).length!==2)throw new Error('BUSINESS_CLIENT_SAVE_PERSISTENCE_ACK_FAILED: adapter boot anchor drifted');const harnessAdapter=adapter.replace(boot,'\n})();');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),clone=v=>JSON.parse(JSON.stringify(v)),fail=m=>{throw new Error('BUSINESS_CLIENT_SAVE_PERSISTENCE_ACK_FAILED: '+m)},ok=(v,l)=>{if(!v)fail(l)},eq=(a,e,l)=>{if(a!==e)fail(`${l}; expected=${e}; actual=${a}`)},same=(a,e,l)=>{if(JSON.stringify(a)!==JSON.stringify(e))fail(`${l}; expected=${JSON.stringify(e)}; actual=${JSON.stringify(a)}`)};
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}}function response(status){return {ok:status>=200&&status<300,status,json:async()=>status>=200&&status<300?({revision:status}):({message:'SYNTHETIC_CLIENT_SAVE_FAILED'})}}function parseState(call){const body=JSON.parse(call?.body||'{}');if(body.rpc!=='crm_save_state')fail(`unexpected rpc=${body.rpc}`);return body.args?.p_state||{}}
const byId=(rows,id)=>Array.isArray(rows)?rows.find(r=>String(r?.id??'')===String(id)):undefined,refs=(rows,id)=>Array.isArray(rows)?rows.filter(r=>String(r?.clientId??'')===String(id)):[];
function makeRuntime({kind='create',first='fail',withBarrier=true}={}){
  const calls={fetch:[],notify:[],navigate:[],hooks:[]},subject={},gate=first==='deferred'?deferred():null;let attempt=0,auditId=0;
  const fetchMock=async(url,options={})=>{calls.fetch.push({url:String(url),body:String(options.body||'')});attempt+=1;if(attempt===1){if(first==='fail')return response(503);if(first==='deferred')return gate.promise}return response(200)};
  const window={__growthOpsVm:subject,location:{hash:'#client-form'}},document={documentElement:{classList:{remove(){},add(){}}},body:{appendChild(){}},createElement:()=>({click(){},remove(){}})};
  vm.runInNewContext(harnessAdapter,{window,document,localStorage:{getItem:()=>null,setItem(){},removeItem(){}},URL:{createObjectURL:()=>'',revokeObjectURL(){}},FileReader:class{},Blob,TextEncoder,structuredClone:globalThis.structuredClone,crypto:globalThis.crypto,console,setTimeout,clearTimeout,Date,Math,JSON,String,Number,Object,Array,Promise,Error,fetch:fetchMock},{timeout:1000});if(!withBarrier)delete subject.persistClientSaveBarrier;
  const existing={id:'client-save-1',name:'Before Save',archived:false,status:'ACTIVE',platform:['TK'],billingMode:'FULL_MONTH',monthlyFee:100,currency:'USD',startDate:'2026-09-01',notes:'client-before',networkEnvironments:[],fbAccounts:[],tkAccounts:[{id:'old-tk'}],googleAccounts:[],instagramAccounts:[]},survivor={id:'client-survivor',name:'Survivor',archived:false,status:'ACTIVE',billingMode:'MANUAL',monthlyFee:0,currency:'USD'},lead={id:'lead-source',company:'Lead Source',stage:'QUALIFIED',nextFollowUp:'2026-09-10',convertedClientId:null,convertedAt:'',notes:'lead-before'},unrelatedLead={id:'lead-survivor',stage:'WON',convertedClientId:'client-survivor',convertedAt:'2026-08-01T00:00:00.000Z'};
  const form=kind==='edit'?{...existing,name:'After Edit',monthlyFee:120}:{id:null,sourceLeadId:'lead-source',name:'Created Client',archived:false,status:'ACTIVE',platform:['TK'],billingMode:'FULL_MONTH',monthlyFee:500,currency:'USD',startDate:'2026-09-01',notes:'form-before',networkEnvironments:[],fbAccounts:[],tkAccounts:[{id:'tk-new',bcId:'bc-new',adAccountId:'ad-new',loginAccount:'login-new',loginPassword:'',twofa:''}],googleAccounts:[],instagramAccounts:[]};
  const selections=kind==='create'?{selectedClientId:'old-client-selection',selectedAssetsClientId:'old-assets-selection',selectedSopClientId:'old-sop-selection',selectedAnalyticsClientId:'old-analytics-selection',selectedAdsClientId:'old-ads-selection'}:{selectedClientId:'client-save-1',selectedAssetsClientId:'client-save-1',selectedSopClientId:'client-save-1',selectedAnalyticsClientId:'client-save-1',selectedAdsClientId:'client-save-1'};
  Object.assign(subject,methods,{clients:kind==='edit'?[existing,survivor]:[survivor],leads:[lead,unrelatedLead],financeReceivables:[{id:'receivable-survivor',clientId:'client-survivor',source:'KEEP'}],financeCosts:[{id:'cost-survivor',clientId:'client-survivor',source:'KEEP'}],standaloneAlerts:[{id:'alert-survivor',clientId:'client-survivor'}],dismissedAlerts:[{id:'dismissed-survivor',clientId:'client-survivor'}],openingProviders:[],openingDeals:[],auditLogs:[{id:'audit-existing',action:'EXISTING',target:'keep'}],backupSnapshots:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],form,formDirty:true,currentPage:'client-form',currentUser:{id:'admin',name:'Admin',role:'ADMIN',enabled:true},...selections,localDateKey:()=> '2026-09-01',$nextTick:fn=>fn?.(),ensureDailyBackup(){},logAudit:(action,target)=>{const row={id:`audit-${++auditId}`,action:String(action),target:String(target)};subject.auditLogs.push(row);return row},notify:m=>calls.notify.push(String(m)),navigateTo:(...args)=>calls.navigate.push(args),ensureClientFirstReceivable:client=>{calls.hooks.push('first');subject.financeReceivables.push({id:`first-${client.id}`,clientId:client.id,source:'FIRST'});return 1},ensureAutomaticReceivables:client=>{calls.hooks.push('receivable');subject.financeReceivables.push({id:`auto-r-${client.id}`,clientId:client.id,source:'AUTO'});return 1},ensureAutomaticAssetCosts:()=>{calls.hooks.push('cost');return 1},collectBackupPayload:()=>({clients:clone(subject.clients),leads:clone(subject.leads),openingProviders:[],openingDeals:[],financeReceivables:clone(subject.financeReceivables),financeCosts:clone(subject.financeCosts),standaloneAlerts:clone(subject.standaloneAlerts),dismissedAlerts:clone(subject.dismissedAlerts),auditLogs:clone(subject.auditLogs),backupSnapshots:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[]})});
  return {subject,calls,existing,lead,selections:clone(selections),resolveFirst:status=>gate?.resolve(response(status))};
}
async function waitFirst(calls){for(let i=0;i<40&&!calls.fetch.length;i+=1)await sleep(10);eq(calls.fetch.length,1,'exactly one pending durable save before ACK')}async function waitRollback(calls){for(let i=0;i<40&&calls.fetch.length<2;i+=1)await sleep(10);ok(calls.fetch.length>=2,'failed ACK enqueues rollback truth');return parseState(calls.fetch.at(-1))}async function later(subject,calls){subject.persist();await sleep(240);return parseState(calls.fetch.at(-1))}
const success=calls=>calls.notify.some(m=>/保存|创建|更新|客户/.test(m)&&!/未保存|失败|不可用/.test(m));
function unrelated(s,label){ok(byId(s.clients,'client-survivor'),`${label} unrelated client`);ok(byId(s.leads,'lead-survivor'),`${label} unrelated lead`);ok(byId(s.financeReceivables,'receivable-survivor'),`${label} unrelated receivable`);ok(byId(s.financeCosts,'cost-survivor'),`${label} unrelated cost`);ok(s.auditLogs.some(r=>r.id==='audit-existing'),`${label} preexisting audit`)}

{
  const {subject:s,calls,resolveFirst}=makeRuntime({kind:'create',first:'deferred'}),task=s.saveClient();ok(task?.then,'create exposes ACK promise');await waitFirst(calls);eq(success(calls),false,'create success held before ACK');eq(calls.navigate.length,0,'create navigation held before ACK');eq(s.formDirty,true,'create dirty held before ACK');for(const h of ['first','receivable','cost'])ok(calls.hooks.includes(h),`create executes ${h} helper`);const pending=parseState(calls.fetch[0]),created=(pending.clients||[]).find(r=>r.name==='Created Client');ok(created,'pending create client');ok(refs(pending.financeReceivables,created.id).length>0,'pending create receivable');const pl=byId(pending.leads,'lead-source');eq(pl?.stage,'WON','pending lead WON');eq(String(pl?.convertedClientId),String(created.id),'pending lead link');ok((pending.auditLogs||[]).some(r=>r.id==='audit-1'),'pending create audit');s.form.notes='user-continued-edit';s.formDirty=true;resolveFirst(200);await task;eq(calls.fetch.length,1,'create single durable save');ok(success(calls),'create success after ACK');ok(calls.navigate.some(a=>a[0]==='client-detail'),'create navigate after ACK');eq(s.form.notes,'user-continued-edit','create preserves form edit during ACK');eq(s.formDirty,true,'create preserves dirty after concurrent form edit');
}
{
  const {subject:s,calls,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'}),task=s.saveClient();ok(task?.then,'edit exposes ACK promise');await waitFirst(calls);eq(success(calls),false,'edit success held before ACK');eq(calls.navigate.length,0,'edit navigation held before ACK');const pending=parseState(calls.fetch[0]);eq(byId(pending.clients,'client-save-1')?.name,'After Edit','pending edited client');ok((pending.auditLogs||[]).some(r=>r.id==='audit-1'),'pending edit audit');resolveFirst(200);await task;eq(calls.fetch.length,1,'edit single durable save');ok(success(calls),'edit success after ACK');ok(calls.navigate.some(a=>a[0]==='client-detail'),'edit navigate after ACK');
}
{
  const {subject:s,calls,lead,selections}=makeRuntime({kind:'create',first:'fail'}),task=s.saveClient();if(task?.then)await task;const attempted=parseState(calls.fetch[0]),created=(attempted.clients||[]).find(r=>r.name==='Created Client');ok(created,'failed create attempted client');ok(!byId(s.clients,created.id),'failed create removes client');eq(lead.stage,'QUALIFIED','failed create restores lead stage');eq(lead.convertedClientId,null,'failed create restores lead pointer');eq(lead.convertedAt,'','failed create restores lead time');eq(lead.nextFollowUp,'2026-09-10','failed create restores followup');eq(refs(s.financeReceivables,created.id).length,0,'failed create removes receivables');for(const [k,v] of Object.entries(selections))eq(s[k],v,`failed create restores ${k}`);eq(s.auditLogs.some(r=>r.id==='audit-1'),false,'failed create removes attempt audit');unrelated(s,'failed create preserves');ok(calls.notify.some(m=>/云端保存失败|未保存/.test(m)),'failed create failure notice');eq(calls.navigate.length,0,'failed create no success navigation');const rollback=await waitRollback(calls);ok(!byId(rollback.clients,created.id),'rollback cloud excludes failed create');eq(byId(rollback.leads,'lead-source')?.stage,'QUALIFIED','rollback cloud restores lead');eq((rollback.auditLogs||[]).some(r=>r.id==='audit-1'),false,'rollback cloud excludes failed audit');const after=await later(s,calls);ok(!byId(after.clients,created.id),'later persist cannot resurrect create');
}
{
  const {subject:s,calls,existing}=makeRuntime({kind:'edit',first:'fail'}),before=clone(existing),task=s.saveClient();if(task?.then)await task;same(byId(s.clients,'client-save-1'),before,'failed edit restores client');eq(refs(s.financeReceivables,'client-save-1').length,0,'failed edit removes receivables');eq(s.auditLogs.some(r=>r.id==='audit-1'),false,'failed edit removes audit');unrelated(s,'failed edit preserves');eq(calls.navigate.length,0,'failed edit no navigation');const rollback=await waitRollback(calls);same(byId(rollback.clients,'client-save-1'),before,'rollback cloud restores edited client');const after=await later(s,calls);same(byId(after.clients,'client-save-1'),before,'later persist cannot resurrect edit');
}
{
  const {subject:s,calls,lead,resolveFirst}=makeRuntime({kind:'create',first:'deferred'}),task=s.saveClient();await waitFirst(calls);const attemptClient=s.clients.find(r=>r.name==='Created Client'),id=attemptClient.id,replacement={...clone(attemptClient),name:'Concurrent Client Replacement'};s.clients.splice(s.clients.indexOf(attemptClient),1,replacement);lead.stage='CONCURRENT_STAGE';lead.convertedClientId='concurrent-client';const attemptReceivable=refs(s.financeReceivables,id)[0];if(attemptReceivable)s.financeReceivables.splice(s.financeReceivables.indexOf(attemptReceivable),1,{...clone(attemptReceivable),source:'CONCURRENT_RECEIVABLE'});s.selectedClientId='concurrent-selection';s.selectedAssetsClientId='concurrent-assets';s.form.notes='concurrent-form-edit';s.formDirty=true;const concurrentAudit={id:'audit-concurrent',action:'CONCURRENT'};s.auditLogs.push(concurrentAudit);resolveFirst(503);await task;eq(byId(s.clients,id)?.name,'Concurrent Client Replacement','create rollback preserves same-ID client replacement');eq(lead.stage,'CONCURRENT_STAGE','create rollback preserves lead field');eq(lead.convertedClientId,'concurrent-client','create rollback preserves lead pointer');if(attemptReceivable)eq(byId(s.financeReceivables,attemptReceivable.id)?.source,'CONCURRENT_RECEIVABLE','create rollback preserves receivable replacement');eq(s.selectedClientId,'concurrent-selection','create rollback preserves selection');eq(s.selectedAssetsClientId,'concurrent-assets','create rollback preserves assets selection');eq(s.form.notes,'concurrent-form-edit','create rollback preserves form edit');eq(s.formDirty,true,'create rollback preserves dirty form');ok(s.auditLogs.includes(concurrentAudit),'create rollback preserves concurrent audit');eq(s.auditLogs.some(r=>r.id==='audit-1'),false,'create rollback removes only attempt audit');const rollback=await waitRollback(calls);eq(byId(rollback.clients,id)?.name,'Concurrent Client Replacement','rollback cloud preserves client replacement');eq(byId(rollback.leads,'lead-source')?.stage,'CONCURRENT_STAGE','rollback cloud preserves lead edit');eq((rollback.auditLogs||[]).some(r=>r.id==='audit-concurrent'),true,'rollback cloud preserves concurrent audit');
}
{
  const {subject:s,calls,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'}),task=s.saveClient();await waitFirst(calls);const live=byId(s.clients,'client-save-1');live.name='Concurrent Same-Object Edit';live.monthlyFee=333;s.form.notes='typing-during-ack';s.formDirty=true;s.auditLogs.push({id:'audit-edit-concurrent',action:'CONCURRENT_EDIT'});resolveFirst(503);await task;eq(byId(s.clients,'client-save-1')?.name,'Concurrent Same-Object Edit','edit rollback preserves same-object name');eq(byId(s.clients,'client-save-1')?.monthlyFee,333,'edit rollback preserves same-object fee');eq(s.form.notes,'typing-during-ack','edit rollback preserves form input');eq(s.formDirty,true,'edit rollback preserves form dirty');ok(s.auditLogs.some(r=>r.id==='audit-edit-concurrent'),'edit rollback preserves concurrent audit');eq(s.auditLogs.some(r=>r.id==='audit-1'),false,'edit rollback removes attempt audit');const rollback=await waitRollback(calls);eq(byId(rollback.clients,'client-save-1')?.name,'Concurrent Same-Object Edit','rollback cloud preserves same-object edit');
}
for(const kind of ['create','edit']){const {subject:s,calls,existing,lead}=makeRuntime({kind,withBarrier:false,first:'deferred'}),beforeClient=clone(existing),beforeLead=clone(lead),result=s.saveClient();if(result?.then)await result;await sleep(20);eq(calls.fetch.length,0,`${kind} missing barrier zero network`);eq(calls.navigate.length,0,`${kind} missing barrier zero navigation`);ok(calls.notify.some(m=>/持久化服务不可用|未保存/.test(m)),`${kind} missing barrier notice`);eq(s.auditLogs.some(r=>r.id==='audit-1'),false,`${kind} missing barrier removes audit`);if(kind==='create'){eq(s.clients.some(r=>r.name==='Created Client'),false,'create missing barrier rolls back client');same(byId(s.leads,'lead-source'),beforeLead,'create missing barrier restores lead')}else same(byId(s.clients,'client-save-1'),beforeClient,'edit missing barrier restores client')}

console.log('BUSINESS_CLIENT_SAVE_PERSISTENCE_ACK_OK: authority=final-app+final-cloud-adapter; create+edit=single-save-success-after-ACK; failure=client+lead+receivable+selection+attempt-audit-rollback+rollback-persisted; later-persist=failed-save-not-resurrected; concurrency=same-id+field-level+receivable-replacement+selection+form-edit+unrelated-audit-preserved; helper-persists=collapsed; missing-barrier=fail-closed');