import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=process.cwd();
const appDir=path.join(root,'dist','app');
const adapterPath=path.join(root,'dist','cloud-adapter.js');
if(!fs.existsSync(appDir)||!fs.existsSync(adapterPath))throw new Error('BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_FAILED: final artifacts missing');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort();
const bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n');

function extract(name){
  const signature=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m');
  const match=signature.exec(bundle);
  if(!match)throw new Error(`BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_FAILED: ${name} missing`);
  const start=match.index+match[0].indexOf(match[1]),tail=bundle.slice(start);
  const defs=[...tail.matchAll(/(?:^|[,]\s*|\n\s*)([A-Za-z_$][A-Za-z0-9_$]*)\s*\([^)]*\)\s*\{/g)];
  if(defs.length<2||defs[0][1]!==name)throw new Error(`BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_FAILED: ${name} parser drifted`);
  const next=defs[1].index+defs[1][0].indexOf(defs[1][1]);
  return tail.slice(0,next).replace(/,\s*$/,'').trim();
}

let methods;
try{methods=vm.runInNewContext(`({${['saveFinanceCost','deleteFinanceCost'].map(extract).join(',')}})`,{Date,Math,Number,String,Object,Array,JSON,Set,Promise},{timeout:1000})}
catch(error){throw new Error(`BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_FAILED: final methods not executable: ${error.message}`)}

const adapter=fs.readFileSync(adapterPath,'utf8');
const bootAnchor='\n  boot();\n})();';
if(adapter.split(bootAnchor).length!==2)throw new Error('BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_FAILED: adapter boot anchor drifted');
const harnessAdapter=adapter.replace(bootAnchor,'\n})();');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const findings=[];
function response(status){return {ok:status>=200&&status<300,status,json:async()=>status>=200&&status<300?({revision:status}):({message:'SYNTHETIC_FINANCE_COST_SAVE_FAILED'})}}
function parseState(call){const body=JSON.parse(call?.body||'{}');if(body.rpc!=='crm_save_state')throw new Error(`BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_FAILED: unexpected rpc=${body.rpc}`);return body.args?.p_state}

function makeRuntime(kind){
  const calls={fetch:[],notify:[]};
  const subject={};
  let saveAttempt=0,confirmAction=null,auditId=0,uid=0;
  const localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
  const window={__growthOpsVm:subject,location:{hash:'#finance'}};
  const document={documentElement:{classList:{remove:()=>{},add:()=>{}}},body:{appendChild:()=>{}},createElement:()=>({click(){},remove(){}})};
  const fetchMock=async(url,options={})=>{calls.fetch.push({url:String(url),body:String(options.body||'')});saveAttempt+=1;return response(saveAttempt===1?503:200)};
  vm.runInNewContext(harnessAdapter,{window,document,localStorage,URL:{createObjectURL:()=>'',revokeObjectURL:()=>{}},FileReader:class{},Blob,TextEncoder,structuredClone,crypto,console,setTimeout,clearTimeout,Date,Math,JSON,String,Number,Object,Array,Promise,Error,fetch:fetchMock},{timeout:1000});

  const existing=kind==='create'?null:{id:'cost-1',date:'2026-09-01',category:'OTHER',scope:'COMPANY',clientId:'',currency:'USD',amount:10,vendor:'Original',note:'original',autoGenerated:false,sourceType:'',sourceId:''};
  const form=kind==='create'
    ?{id:'',date:'2026-09-04',category:'OTHER',scope:'COMPANY',clientId:'',currency:'USD',amount:'25',vendor:'New Vendor',note:'new'}
    :{...structuredClone(existing),date:'2026-09-04',currency:'CNY',amount:'35',vendor:'Edited Vendor',note:'edited'};
  Object.assign(subject,methods,{
    currentUser:{id:'finance',name:'Finance User',role:'FINANCE',enabled:true},clients:[],financeCosts:existing?[existing]:[],auditLogs:[],
    financeReceivables:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],backupSnapshots:[],
    costForm:form,showCostModal:true,
    normalizeFinanceCost:value=>structuredClone(value||{}),assertMonthUnlocked:()=>true,isMonthLocked:()=>false,
    accountUid:prefix=>`${prefix}-${++uid}`,financeCostCategoryText:value=>String(value||''),financeCostScopeText:value=>String(value?.scope||value||''),formatMoney:(value,currency)=>`${currency||'USD'}:${Number(value)}`,
    askConfirm:(_config,action)=>{confirmAction=action},
    logAudit:(action,target)=>{const row={id:`audit-${++auditId}`,action:String(action),target:String(target)};subject.auditLogs.push(row);return row},
    notify:message=>calls.notify.push(String(message)),ensureDailyBackup:()=>{},
    collectBackupPayload:()=>({clients:[],financeReceivables:[],financeCosts:structuredClone(subject.financeCosts),financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],auditLogs:structuredClone(subject.auditLogs),backupSnapshots:[]}),
  });
  return {subject,existing,calls,getConfirm:()=>confirmAction};
}

async function settleFirstFailure(calls){await sleep(260);if(calls.fetch.length<1)throw new Error('BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_FAILED: expected first cloud save attempt')}
async function laterPersist(subject,calls){subject.persist();await sleep(260);if(calls.fetch.length<2)throw new Error('BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_FAILED: expected later cloud save attempt');return parseState(calls.fetch.at(-1))}

// CREATE: manual cost success currently precedes durable acknowledgement. A failed
// first cloud save leaves the cost and audit live, and a later unrelated persist can
// make that failed accounting mutation durable.
{
  const {subject,calls}=makeRuntime('create');subject.saveFinanceCost();
  if(subject.showCostModal===false||calls.notify.some(m=>m.includes('成本已保存')))findings.push('saveFinanceCost create announces/closes before durable ACK');
  await settleFirstFailure(calls);
  const created=subject.financeCosts.find(c=>c.vendor==='New Vendor');
  if(created&&subject.auditLogs.some(a=>a.action==='新增成本'))findings.push('saveFinanceCost create 503 leaves false cost/audit in memory');
  const later=await laterPersist(subject,calls);
  if(later.financeCosts.some(c=>c.vendor==='New Vendor')&&later.auditLogs.some(a=>a.action==='新增成本'))findings.push('saveFinanceCost create later persist makes failed create durable');
}

// EDIT: the original cost is an accounting basis. Failed persistence must not leave
// the edited amount/currency/audit available for a later save to serialize.
{
  const {subject,calls}=makeRuntime('edit');subject.saveFinanceCost();
  if(subject.showCostModal===false||calls.notify.some(m=>m.includes('成本已保存')))findings.push('saveFinanceCost edit announces/closes before durable ACK');
  await settleFirstFailure(calls);
  const edited=subject.financeCosts.find(c=>c.id==='cost-1');
  if(edited?.amount===35&&edited?.currency==='CNY'&&subject.auditLogs.some(a=>a.action==='修改成本'))findings.push('saveFinanceCost edit 503 leaves edited cost/audit in memory');
  const later=await laterPersist(subject,calls),laterCost=later.financeCosts.find(c=>c.id==='cost-1');
  if(laterCost?.amount===35&&laterCost?.currency==='CNY'&&later.auditLogs.some(a=>a.action==='修改成本'))findings.push('saveFinanceCost edit later persist makes failed edit durable');
}

// DELETE: confirmation-time live-target/automatic-cost/month-lock checks are already
// hardened. This probe isolates the durability gap after a valid manual delete confirm.
{
  const {subject,existing,calls,getConfirm}=makeRuntime('delete');subject.deleteFinanceCost(existing);const confirm=getConfirm();if(typeof confirm!=='function')throw new Error('BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_FAILED: delete confirmation missing');confirm();
  if(calls.notify.some(m=>m.includes('已删除')))findings.push('deleteFinanceCost announces success before durable ACK');
  await settleFirstFailure(calls);
  if(!subject.financeCosts.some(c=>c.id==='cost-1')&&subject.auditLogs.some(a=>a.action==='删除成本'))findings.push('deleteFinanceCost 503 leaves false deletion/audit in memory');
  const later=await laterPersist(subject,calls);
  if(!later.financeCosts.some(c=>c.id==='cost-1')&&later.auditLogs.some(a=>a.action==='删除成本'))findings.push('deleteFinanceCost later persist makes failed deletion durable');
}

if(findings.length)throw new Error(`BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_FINDINGS: count=${findings.length}; ${findings.join(' | ')}`);
console.log('BUSINESS_FINANCE_COST_PERSISTENCE_ACK_PROBE_SAFE: manual-create+edit+delete=durable-ack-safe');
