import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const appDir=path.join(process.cwd(),'dist','app');
if(!fs.existsSync(appDir))throw new Error('BUSINESS_CLIENT_REMINDER_MONEY_MUTATIONS_FAILED: dist/app missing');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort();
if(!files.length)throw new Error('BUSINESS_CLIENT_REMINDER_MONEY_MUTATIONS_FAILED: no app-inline JS');
const bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n');

function extractMethod(name){
  const signature=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m'),match=signature.exec(bundle);
  if(!match)throw new Error(`BUSINESS_CLIENT_REMINDER_MONEY_MUTATIONS_FAILED: ${name} not found`);
  const start=match.index+match[0].indexOf(match[1]),open=bundle.indexOf('{',start);
  let depth=0,quote='',escaped=false,lineComment=false,blockComment=false;
  for(let i=open;i<bundle.length;i+=1){const ch=bundle[i],next=bundle[i+1]||'';if(lineComment){if(ch==='\n')lineComment=false;continue}if(blockComment){if(ch==='*'&&next==='/'){blockComment=false;i+=1}continue}if(quote){if(escaped)escaped=false;else if(ch==='\\')escaped=true;else if(ch===quote)quote='';continue}if(ch==='/'&&next==='/'){lineComment=true;i+=1;continue}if(ch==='/'&&next==='*'){blockComment=true;i+=1;continue}if(ch==='"'||ch==="'"||ch==='`'){quote=ch;continue}if(ch==='{')depth+=1;else if(ch==='}'&&--depth===0)return bundle.slice(start,i+1).trim()}
  throw new Error(`BUSINESS_CLIENT_REMINDER_MONEY_MUTATIONS_FAILED: ${name} closing brace missing`);
}

const methodNames=['saveRecharge','saveRechargeReminder','saveRenewal','saveStandaloneAlert'],methods={};
for(const name of methodNames){const source=extractMethod(name),compiled=vm.runInNewContext(`({${source}})`,{Number,String,Object,Array,Math,Set,JSON,Date,Promise,Error},{timeout:1000});if(typeof compiled[name]!=='function')throw new Error(`BUSINESS_CLIENT_REMINDER_MONEY_MUTATIONS_FAILED: ${name} not executable`);methods[name]=compiled[name]}
const fail=m=>{throw new Error('BUSINESS_CLIENT_REMINDER_MONEY_MUTATIONS_FAILED: '+m)},eq=(a,b,m)=>{if(a!==b)fail(`${m}; expected=${JSON.stringify(b)}; actual=${JSON.stringify(a)}`)},ok=(v,m)=>{if(!v)fail(m)};

function rechargeContext(amount,{locked=false,accountExists=true}={}){const account={id:'acct-1',rechargeHistory:[]},notices=[],audits=[];let persistCount=0,barrierCount=0,lockChecks=0;const ctx={rechargeForm:{clientId:'client-1',platform:'FB',accountId:'acct-1',clientName:'Client One',accountName:'Account One',date:'2026-09-02',currency:'USD',amount,note:'topup'},showRechargeModal:true,findAccount(){return accountExists?account:null},assertMonthUnlocked(month){lockChecks+=1;eq(month,'2026-09','recharge lock month');return !locked},localDateKey(){return'2026-09-02'},persist(){persistCount+=1},persistRechargeBarrier(){barrierCount+=1;return Promise.resolve(true)},logAudit(action,detail){audits.push([action,detail])},notify(message){notices.push(message)},formatMoney(value,currency){return`${currency} ${value}`},hasUsdBalanceData(){return false},accountBalanceText(){return'$0'}};return{ctx,account,notices,audits,get persistCount(){return persistCount},get barrierCount(){return barrierCount},get lockChecks(){return lockChecks}}}

{const state=rechargeContext('125.50');await methods.saveRecharge.call(state.ctx);eq(state.account.rechargeHistory.length,1,'valid recharge row');eq(state.account.rechargeHistory[0].amount,125.5,'valid recharge numeric');eq(state.persistCount,0,'valid recharge legacy persist suppressed');eq(state.barrierCount,1,'valid recharge durable barrier');eq(state.audits.length,1,'valid recharge audit');eq(state.ctx.showRechargeModal,false,'valid recharge modal closes after ACK')}
{const state=rechargeContext('50',{locked:true});methods.saveRecharge.call(state.ctx);eq(state.account.rechargeHistory.length,0,'locked recharge mutation');eq(state.persistCount,0,'locked recharge persist');eq(state.barrierCount,0,'locked recharge barrier');eq(state.audits.length,0,'locked recharge audit');eq(state.lockChecks,1,'locked recharge check')}
for(const amount of ['0','-1','not-a-number','Infinity']){const state=rechargeContext(amount);methods.saveRecharge.call(state.ctx);eq(state.account.rechargeHistory.length,0,`invalid recharge mutation ${amount}`);eq(state.persistCount,0,`invalid recharge persist ${amount}`);eq(state.barrierCount,0,`invalid recharge barrier ${amount}`);eq(state.audits.length,0,`invalid recharge audit ${amount}`);ok(state.notices.some(m=>String(m).includes('有效的充值金额')),`invalid recharge notice ${amount}`)}
{const state=rechargeContext('50',{accountExists:false});methods.saveRecharge.call(state.ctx);eq(state.persistCount,0,'missing account persist');eq(state.barrierCount,0,'missing account barrier');eq(state.audits.length,0,'missing account audit');eq(state.ctx.showRechargeModal,false,'missing account modal')}
{let persistCount=0;methods.saveRechargeReminder.call({persist(){persistCount+=1}},{id:'acct-1'});eq(persistCount,1,'recharge reminder persist');methods.saveRechargeReminder.call({persist(){persistCount+=1}},null);eq(persistCount,1,'missing recharge reminder no-op')}

function renewalContext({target,standaloneAlerts=[],clients=[],dismissedAlerts=[]}){const notices=[],audits=[],autoBillCalls=[],networkSyncCalls=[];let persistCount=0,barrierCount=0;const ctx={renewalTarget:target,renewalForm:{newDueDate:'2026-12-31',note:'renewed'},standaloneAlerts,clients,dismissedAlerts,financeReceivables:[],auditLogs:[],showRenewalModal:true,localDateKey(){return'2026-09-02'},syncLegacyNetworkFields(client){networkSyncCalls.push(client)},ensureAutomaticReceivables(args){autoBillCalls.push(args);return 2},persist(){persistCount+=1},persistRenewalBarrier(){barrierCount+=1;return Promise.resolve(true)},logAudit(action,detail){audits.push([action,detail]);const row={action,detail};ctx.auditLogs.push(row);return row},notify(message){notices.push(message)},alertTypeName(key){return key}};return{ctx,notices,audits,autoBillCalls,networkSyncCalls,get persistCount(){return persistCount},get barrierCount(){return barrierCount}}}

// Standalone renewal: live target ACKs once; stale target remains fail-closed.
{const alert={id:'sa-1',dueDate:'2026-10-01'},target={id:'sa-1',isStandalone:true,typeKey:'IP',dueDate:'2026-10-01',clientName:'Manual',type:'IP'},state=renewalContext({target,standaloneAlerts:[alert],dismissedAlerts:[{id:'sa-1'},{id:'keep'}]});await methods.saveRenewal.call(state.ctx);eq(alert.dueDate,'2026-12-31','standalone renewal date');eq(state.ctx.dismissedAlerts.length,1,'standalone dismissal cleanup');eq(state.ctx.dismissedAlerts[0].id,'keep','standalone unrelated dismissal');eq(state.persistCount,0,'standalone legacy persist suppressed');eq(state.barrierCount,1,'standalone durable barrier');eq(state.audits.length,1,'standalone audit');eq(state.autoBillCalls.length,0,'standalone no auto billing')}
{const target={id:'sa-missing',isStandalone:true,typeKey:'IP',dueDate:'2026-10-01',clientName:'Manual',type:'IP'},state=renewalContext({target,standaloneAlerts:[],dismissedAlerts:[{id:'sa-missing'}]});methods.saveRenewal.call(state.ctx);eq(state.ctx.dismissedAlerts.length,1,'stale standalone dismissal');eq(state.persistCount,0,'stale standalone persist');eq(state.barrierCount,0,'stale standalone barrier');eq(state.audits.length,0,'stale standalone audit');eq(state.autoBillCalls.length,0,'stale standalone auto billing');eq(state.ctx.showRenewalModal,true,'stale standalone modal');ok(state.notices.some(m=>String(m).includes('不存在')||String(m).includes('刷新')),'stale standalone notice')}

// Contract renewal: CAS guard + automatic receivable completion + durable ACK.
{const client={id:'client-1',endDate:'2026-10-01',renewalHistory:[]},target={id:'contract-client-1',isStandalone:false,typeKey:'CONTRACT',dueDate:'2026-10-01',clientId:'client-1',clientName:'Client One',type:'合同'},state=renewalContext({target,clients:[client],dismissedAlerts:[{id:'contract-client-1'}]});await methods.saveRenewal.call(state.ctx);eq(client.endDate,'2026-12-31','contract renewal date');eq(client.renewalHistory.length,1,'contract renewal history');eq(state.autoBillCalls.length,1,'contract auto billing');eq(state.persistCount,0,'contract legacy persist suppressed');eq(state.barrierCount,1,'contract durable barrier');eq(state.audits.length,1,'contract outer audit')}
{const client={id:'client-1',endDate:'2027-01-31',renewalHistory:[]},target={id:'contract-client-1',isStandalone:false,typeKey:'CONTRACT',dueDate:'2026-10-01',clientId:'client-1',clientName:'Client One',type:'合同'},state=renewalContext({target,clients:[client],dismissedAlerts:[{id:'contract-client-1'}]});methods.saveRenewal.call(state.ctx);eq(client.endDate,'2027-01-31','stale contract date');eq(client.renewalHistory.length,0,'stale contract history');eq(state.autoBillCalls.length,0,'stale contract auto billing');eq(state.persistCount,0,'stale contract persist');eq(state.barrierCount,0,'stale contract barrier');eq(state.audits.length,0,'stale contract audit');ok(state.notices.some(m=>String(m).includes('变化')||String(m).includes('刷新')),'stale contract notice')}

// Modern IP renewals are exact-environment scoped and stale-safe.
{const env={id:'net-1',ipDueDate:'2026-10-01'},client={id:'client-1',ipDueDate:'2026-11-15',networkEnvironments:[env]},target={id:'ip-client-1-net-1',isStandalone:false,typeKey:'IP',networkId:'net-1',dueDate:'2026-10-01',clientId:'client-1',clientName:'Client One',type:'IP'},state=renewalContext({target,clients:[client],dismissedAlerts:[{id:target.id}]});await methods.saveRenewal.call(state.ctx);eq(env.ipDueDate,'2026-12-31','modern IP date');eq(client.ipDueDate,'2026-11-15','modern IP legacy root untouched by test sync');eq(state.networkSyncCalls.length,1,'modern IP sync');eq(state.autoBillCalls.length,0,'modern IP no auto billing');eq(state.persistCount,0,'modern IP legacy persist suppressed');eq(state.barrierCount,1,'modern IP durable barrier');eq(state.audits.length,1,'modern IP audit')}
{const env={id:'net-1',ipDueDate:'2027-01-31'},client={id:'client-1',ipDueDate:'2026-11-15',networkEnvironments:[env]},target={id:'ip-client-1-net-1',isStandalone:false,typeKey:'IP',networkId:'net-1',dueDate:'2026-10-01',clientId:'client-1',clientName:'Client One',type:'IP'},state=renewalContext({target,clients:[client],dismissedAlerts:[{id:target.id}]});methods.saveRenewal.call(state.ctx);eq(env.ipDueDate,'2027-01-31','stale modern IP date');eq(state.networkSyncCalls.length,0,'stale modern IP no sync');eq(state.persistCount,0,'stale modern IP persist');eq(state.barrierCount,0,'stale modern IP barrier');eq(state.audits.length,0,'stale modern IP audit')}
{const client={id:'client-1',ipDueDate:'2026-10-01',networkEnvironments:[]},target={id:'ip-client-1-net-missing',isStandalone:false,typeKey:'IP',networkId:'net-missing',dueDate:'2026-10-01',clientId:'client-1',clientName:'Client One',type:'IP'},state=renewalContext({target,clients:[client],dismissedAlerts:[{id:target.id}]});methods.saveRenewal.call(state.ctx);eq(client.ipDueDate,'2026-10-01','missing modern IP no legacy fallback');eq(state.networkSyncCalls.length,0,'missing modern IP no sync');eq(state.persistCount,0,'missing modern IP persist');eq(state.barrierCount,0,'missing modern IP barrier');eq(state.audits.length,0,'missing modern IP audit');ok(state.notices.some(m=>String(m).includes('不存在')||String(m).includes('刷新')),'missing modern IP notice')}

// Legacy root IP remains supported, but is still compare-and-set guarded.
{const client={id:'client-1',ipDueDate:'2026-10-01',networkEnvironments:[]},target={id:'ip-client-1-legacy',isStandalone:false,typeKey:'IP',dueDate:'2026-10-01',clientId:'client-1',clientName:'Client One',type:'IP'},state=renewalContext({target,clients:[client],dismissedAlerts:[{id:target.id}]});await methods.saveRenewal.call(state.ctx);eq(client.ipDueDate,'2026-12-31','legacy IP date');eq(state.networkSyncCalls.length,1,'legacy IP sync');eq(state.persistCount,0,'legacy IP legacy persist suppressed');eq(state.barrierCount,1,'legacy IP durable barrier');eq(state.audits.length,1,'legacy IP audit')}
{const client={id:'client-1',ipDueDate:'2027-01-31',networkEnvironments:[]},target={id:'ip-client-1-legacy',isStandalone:false,typeKey:'IP',dueDate:'2026-10-01',clientId:'client-1',clientName:'Client One',type:'IP'},state=renewalContext({target,clients:[client],dismissedAlerts:[{id:target.id}]});methods.saveRenewal.call(state.ctx);eq(client.ipDueDate,'2027-01-31','stale legacy IP date');eq(state.networkSyncCalls.length,0,'stale legacy IP no sync');eq(state.persistCount,0,'stale legacy IP persist');eq(state.barrierCount,0,'stale legacy IP barrier');eq(state.audits.length,0,'stale legacy IP audit')}

// Standalone alert creation retains the existing type guard and legacy persistence contract.
{let persistCount=0,auditCount=0;const ctx={reminderTypeOptions:[{key:'IP'}],newAlertForm:{typeKey:'UNKNOWN',clientName:'X',dueDate:'2026-10-01',cost:'',target:''},standaloneAlerts:[],showAddAlertModal:true,persist(){persistCount+=1},logAudit(){auditCount+=1},notify(){}};methods.saveStandaloneAlert.call(ctx);eq(ctx.standaloneAlerts.length,0,'invalid standalone type');eq(persistCount,0,'invalid standalone persist');eq(auditCount,0,'invalid standalone audit')}

console.log('BUSINESS_CLIENT_REMINDER_MONEY_MUTATIONS_OK: recharge=finite-positive+month-lock+durable-ACK; recharge-reminder=persist-only; renewal=standalone+contract+ip-exact-source+stale-fail-closed+auto-billing+durable-ACK; standalone-alert=type-guard; persist+audit=phase-pinned');
await import('./test_business_renewal_persistence_ack.mjs');
