import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const appDir=path.join(process.cwd(),'dist','app');
if(!fs.existsSync(appDir))throw new Error('BUSINESS_AD_DATA_PERSISTENCE_ACK_FAILED: dist/app missing');
const files=fs.readdirSync(appDir).filter(n=>/^app-inline-\d+\.js$/.test(n)).sort(),bundle=files.map(n=>fs.readFileSync(path.join(appDir,n),'utf8')).join('\n');
function extract(name){const m=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m').exec(bundle);if(!m)throw new Error(`BUSINESS_AD_DATA_PERSISTENCE_ACK_FAILED: ${name} missing`);const s=m.index+m[0].indexOf(m[1]),o=bundle.indexOf('{',s);let d=0,q='',e=false,lc=false,bc=false;for(let i=o;i<bundle.length;i++){const c=bundle[i],n=bundle[i+1]||'';if(lc){if(c==='\n')lc=false;continue}if(bc){if(c==='*'&&n==='/'){bc=false;i++}continue}if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q='';continue}if(c==='/'&&n==='/'){lc=true;i++;continue}if(c==='/'&&n==='*'){bc=true;i++;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return bundle.slice(s,i+1)}throw new Error(`BUSINESS_AD_DATA_PERSISTENCE_ACK_FAILED: ${name} boundary`)}
const methods=vm.runInNewContext(`({${['saveAdDataRecord','deleteAdDataRecord','saveAdSpend'].map(extract).join(',')}})`,{Date,Math,Number,String,Object,Array,JSON,Set,Promise,Error},{timeout:1000});
const clone=v=>JSON.parse(JSON.stringify(v)),fail=m=>{throw new Error('BUSINESS_AD_DATA_PERSISTENCE_ACK_FAILED: '+m)},eq=(a,b,m)=>{if(a!==b)fail(`${m}; expected=${b}; actual=${a}`)},same=(a,b,m)=>{if(JSON.stringify(a)!==JSON.stringify(b))fail(`${m}; expected=${JSON.stringify(b)}; actual=${JSON.stringify(a)}`)},ok=(v,m)=>{if(!v)fail(m)};
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject}}
function make({barrier='deferred',record=true}={}){const gate=deferred(),calls={notify:[],persist:0,barrier:0,audit:0,confirm:null},campaign={id:'camp1',name:'Campaign',planName:'Plan',updatedAt:'OLD',adSets:[]},existing={id:'r1',date:'2026-09-08',campaignId:'camp1',currency:'USD',spend:5,impressions:100,clicks:10,leads:2,conversions:1,revenue:20,createdAt:'OLD',updatedAt:'OLD'},account={id:'a1',accountName:'Account',adSpend:record?5:0,adSpendCurrency:'USD',adDataRecords:record?[existing]:[]},client={id:'c1',name:'Client',fbAccounts:[account],tkAccounts:[],fbData:record?{_source:'AD_RECORDS',spend:5}:{legacy:true}},subject={...methods,clients:[client],selectedAdsClient:client,selectedAdsAccount:account,selectedAdsPlatform:'FB',savedAdsCampaignsForAccount:[campaign],editingAdDataRecordId:record?'r1':null,showAdDataModal:true,adDataForm:{date:'2026-09-08',campaignId:'camp1',adSetId:'',adId:'',currency:'USD',spend:'12',impressions:'120',reach:'100',clicks:'12',leads:'3',conversions:'2',revenue:'30',video3sRate:'',video25Rate:'',video50Rate:'',video75Rate:'',video95Rate:'',videoCompleteRate:'',note:'n'},auditLogs:[{id:'old'}],localDateKey:()=> '2026-09-08',assertMonthUnlocked:()=>true,adDataIdentity:r=>[r?.date||'',r?.campaignId||'',r?.adSetId||'',r?.adId||''].join('|'),normalizePercent:v=>v===''?null:Number(v),accountUid:()=> 'new-r',formatMoney:(v,c)=>`${c}:${v}`,syncAccountAnalyticsFromRecords(a){a.adSpend=(a.adDataRecords||[]).reduce((s,r)=>s+Number(r.spend||0),0);a.adSpendCurrency='USD'},syncClientPlatformAnalytics(c){c.fbData={_source:'AD_RECORDS',spend:account.adSpend,records:account.adDataRecords.length}},persist(){calls.persist++},logAudit(action,target){calls.audit++;const row={id:`audit-${calls.audit}`,action,target};subject.auditLogs.push(row);return row},notify(m){calls.notify.push(String(m))},askConfirm(_o,cb){calls.confirm=cb}};subject.persistAdStructureBarrier=()=>{calls.barrier++;if(barrier==='ok')return Promise.resolve(true);if(barrier==='fail')return Promise.reject(new Error('SYNTHETIC'));return gate.promise};return{subject,client,account,campaign,existing,calls,gate}}

// Save/edit success is tentative until ACK; modal/editing UI stays open while pending.
{const {subject,account,calls,gate}=make(),task=subject.saveAdDataRecord();ok(task&&typeof task.then==='function','save returns ACK promise');eq(calls.barrier,1,'save barrier once');eq(account.adDataRecords[0].spend,12,'tentative edited record');eq(subject.showAdDataModal,true,'modal remains open before ACK');eq(subject.editingAdDataRecordId,'r1','editing id remains before ACK');eq(calls.notify.length,0,'success notice held');gate.resolve(true);await task;eq(subject.showAdDataModal,false,'modal closes after ACK');eq(subject.editingAdDataRecordId,null,'editing clears after ACK');ok(calls.notify.some(m=>m.includes('已更新')),'save success after ACK');eq(calls.persist,0,'legacy persist suppressed')}

// Save failure restores record + derived account/client analytics + campaign timestamp + audit truth.
{const {subject,client,account,campaign,calls}=make({barrier:'fail'}),before={record:clone(account.adDataRecords),spend:account.adSpend,currency:account.adSpendCurrency,fb:clone(client.fbData),updated:campaign.updatedAt,audits:clone(subject.auditLogs)};await subject.saveAdDataRecord();same(account.adDataRecords,before.record,'save failure records rollback');eq(account.adSpend,before.spend,'save failure account spend rollback');eq(account.adSpendCurrency,before.currency,'save failure currency rollback');same(client.fbData,before.fb,'save failure client analytics rollback');eq(campaign.updatedAt,before.updated,'save failure campaign timestamp rollback');same(subject.auditLogs,before.audits,'save failure attempt audit rollback');eq(calls.persist,1,'save failure persists rollback truth');eq(subject.showAdDataModal,true,'save failure keeps modal');eq(subject.editingAdDataRecordId,'r1','save failure keeps editing id')}

// Concurrent state wins over failed save rollback.
{const {subject,client,account,calls,gate}=make(),task=subject.saveAdDataRecord();account.adDataRecords.push({id:'concurrent',date:'2026-09-08',spend:1,currency:'USD'});account.adSpend=999;client.fbData={concurrent:true};gate.reject(new Error('SYNTHETIC'));await task;ok(account.adDataRecords.some(r=>r.id==='concurrent'),'concurrent record preserved');eq(account.adSpend,999,'concurrent account aggregate preserved');same(client.fbData,{concurrent:true},'concurrent client analytics preserved');eq(calls.persist,1,'concurrent failure persists current truth')}

// Delete confirmation path uses ACK and rolls back record + derived analytics on failure.
{const {subject,client,account,existing,calls,gate}=make();subject.deleteAdDataRecord(existing);ok(typeof calls.confirm==='function','delete opens confirmation');const task=calls.confirm();ok(task&&typeof task.then==='function','delete callback returns ACK promise');eq(account.adDataRecords.length,0,'delete tentative removal');eq(subject.editingAdDataRecordId,'r1','editing id held before delete ACK');eq(calls.notify.length,0,'delete success held');gate.reject(new Error('SYNTHETIC'));await task;eq(account.adDataRecords.length,1,'failed delete restores record');eq(account.adDataRecords[0].id,'r1','failed delete restores target id');eq(account.adSpend,5,'failed delete restores account spend');same(client.fbData,{_source:'AD_RECORDS',spend:5},'failed delete restores client analytics');eq(subject.editingAdDataRecordId,'r1','failed delete preserves editor');eq(calls.persist,1,'failed delete persists rollback truth')}

// Manual account spend save is ACK-gated and field-CAS rollback preserves newer edits.
{const {subject,account,calls,gate}=make();account.adSpend='22.5';const task=subject.saveAdSpend(account);eq(account.adSpend,22.5,'spend normalized tentatively');eq(calls.notify.length,0,'spend success held');gate.resolve(true);await task;ok(calls.notify.includes('广告消耗已保存'),'spend success after ACK');eq(calls.persist,0,'spend legacy persist suppressed')}
{const {subject,account,calls,gate}=make();account.adSpend='22.5';const task=subject.saveAdSpend(account);account.adSpend=77;gate.reject(new Error('SYNTHETIC'));await task;eq(account.adSpend,77,'concurrent spend edit preserved');eq(calls.persist,1,'spend failure persists rollback truth')}

// Missing durability service restores tentative operation and performs zero cloud/debounced writes.
{const {subject,account,calls}=make();delete subject.persistAdStructureBarrier;const before=clone(account.adDataRecords);const result=subject.saveAdDataRecord();eq(result,undefined,'missing barrier save returns synchronously');same(account.adDataRecords,before,'missing barrier restores record state');eq(calls.persist,0,'missing barrier zero persist');ok(calls.notify.some(m=>m.includes('持久化服务不可用')),'missing barrier notice')}

console.log('BUSINESS_AD_DATA_PERSISTENCE_ACK_OK: final-runtime record-save+delete+manual-spend=success-after-shared-ACK; failure=record+derived-account/client-analytics+campaign+audit rollback+rollback-persisted; concurrency=array+field authority preserved; modal/editing success UI ACK-gated; missing-barrier=fail-closed');
await import('./test_business_recharge_persistence_ack.mjs');
