import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const appDir=path.join(process.cwd(),'dist','app');
if(!fs.existsSync(appDir))throw new Error('BUSINESS_OPENING_COST_MONTH_LOCK_FAILED: dist/app missing; run canonical build first');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort();
if(!files.length)throw new Error('BUSINESS_OPENING_COST_MONTH_LOCK_FAILED: no final app-inline JS artifacts');
const bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n');

function extractMethod(name){
  const signature=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m');
  const match=signature.exec(bundle);
  if(!match)throw new Error(`BUSINESS_OPENING_COST_MONTH_LOCK_FAILED: final runtime ${name} not found`);
  const start=match.index+match[0].indexOf(match[1]);
  const tail=bundle.slice(start);
  const defs=[...tail.matchAll(/(?:^|[,]\s*|\n\s*)([A-Za-z_$][A-Za-z0-9_$]*)\s*\([^)]*\)\s*\{/g)];
  if(defs.length<2||defs[0][1]!==name)throw new Error(`BUSINESS_OPENING_COST_MONTH_LOCK_FAILED: ${name} parser drifted`);
  const next=defs[1].index+defs[1][0].indexOf(defs[1][1]);
  return tail.slice(0,next).replace(/,\s*$/,'').trim();
}

let syncOpeningFeeCost;
try{
  ({syncOpeningFeeCost}=vm.runInNewContext(`({${extractMethod('syncOpeningFeeCost')}})`,{Number,String,Object,Array,Math,Set,JSON},{timeout:1000}));
}catch(error){
  throw new Error(`BUSINESS_OPENING_COST_MONTH_LOCK_FAILED: unable to execute final method: ${error.message}`);
}
if(typeof syncOpeningFeeCost!=='function')throw new Error('BUSINESS_OPENING_COST_MONTH_LOCK_FAILED: syncOpeningFeeCost is not executable');

const fail=message=>{throw new Error('BUSINESS_OPENING_COST_MONTH_LOCK_FAILED: '+message)};
const eq=(actual,expected,label)=>{if(actual!==expected)fail(`${label}; expected=${expected}; actual=${actual}`)};
const ok=(value,label)=>{if(!value)fail(label)};
const clone=value=>JSON.parse(JSON.stringify(value));

const deal=(overrides={})=>({
  id:'deal-1',status:'OPENED',clientId:'client-1',fee:100,currency:'USD',
  effectiveStartDate:'2026-09-01',expectedDate:'2026-09-01',submitDate:'2026-08-20',
  platform:'FB',accountType:'广告账户',partnerName:'Provider A',...overrides,
});
const cost=(overrides={})=>({
  id:'cost-opening-1',date:'2026-08-15',category:'OPENING',scope:'CLIENT',clientId:'client-1',
  currency:'USD',amount:100,vendor:'Provider A',note:'开户渠道自动成本 · Facebook · 广告账户',
  sourceType:'OPENING_DEAL',sourceId:'deal-1',autoGenerated:true,...overrides,
});
const subject=(overrides={})=>({
  syncOpeningFeeCost,financeCosts:[],
  isMonthLocked:month=>month==='2026-08',
  openingProvider:()=>({name:'Provider A'}),
  normalizeFinanceCost:value=>({...value}),
  accountUid:()=> 'cost-opening-new',
  localDateKey:()=> '2026-09-01',
  notify:()=>{},
  ...overrides,
});

// A cost that already belongs to a locked month is historical finance truth.
// Editing the source opening deal must not relocate or rewrite it merely because
// the destination month is still open.
{
  const existing=cost();
  const before=clone(existing);
  const notices=[];
  const s=subject({financeCosts:[existing],notify:m=>notices.push(m)});
  const changed=s.syncOpeningFeeCost(deal({effectiveStartDate:'2026-09-10',fee:250,currency:'CNY',clientId:'client-2'}),{silent:false});
  eq(changed,0,'locked-origin opening cost must report no mutation');
  eq(s.financeCosts.length,1,'locked-origin opening cost row count preserved');
  eq(JSON.stringify(s.financeCosts[0]),JSON.stringify(before),'locked-origin opening cost must remain byte-for-byte unchanged');
  ok(notices.some(m=>m.includes('2026-08')&&m.includes('已月结')),'locked-origin opening cost should explain original locked month');
}

// Destination lock remains authoritative for an otherwise editable source cost.
{
  const existing=cost({date:'2026-09-01'});
  const before=clone(existing);
  const s=subject({financeCosts:[existing],isMonthLocked:month=>month==='2026-10'});
  const changed=s.syncOpeningFeeCost(deal({effectiveStartDate:'2026-10-05',fee:300}),{silent:true});
  eq(changed,0,'locked-destination opening cost must report no mutation');
  eq(JSON.stringify(s.financeCosts[0]),JSON.stringify(before),'locked-destination opening cost must remain unchanged');
}

// Unlocked-to-unlocked edits still update the same automatic cost row.
{
  const existing=cost({date:'2026-09-01'});
  const s=subject({financeCosts:[existing],isMonthLocked:()=>false});
  const changed=s.syncOpeningFeeCost(deal({effectiveStartDate:'2026-10-05',fee:300,currency:'CNY',clientId:'client-2'}),{silent:true});
  eq(changed,1,'unlocked opening cost edit should mutate');
  eq(s.financeCosts.length,1,'unlocked opening cost edit must not duplicate');
  eq(s.financeCosts[0].id,'cost-opening-1','unlocked opening cost edit preserves id');
  eq(s.financeCosts[0].date,'2026-10-05','unlocked opening cost edit updates date');
  eq(s.financeCosts[0].amount,300,'unlocked opening cost edit updates amount');
  eq(s.financeCosts[0].currency,'CNY','unlocked opening cost edit updates currency');
  eq(s.financeCosts[0].clientId,'client-2','unlocked opening cost edit updates client');
}

// Disqualifying/deleting a linked cost is already origin-month guarded.
{
  const existing=cost();
  const s=subject({financeCosts:[existing]});
  const changed=s.syncOpeningFeeCost(deal({status:'REJECTED'}),{silent:true});
  eq(changed,0,'locked-origin disqualification reports no mutation');
  eq(s.financeCosts.length,1,'locked-origin disqualification must preserve historical cost');
}
{
  const existing=cost({date:'2026-09-01'});
  const s=subject({financeCosts:[existing],isMonthLocked:()=>false});
  s.syncOpeningFeeCost(deal({status:'REJECTED'}),{silent:true});
  eq(s.financeCosts.length,0,'unlocked-origin disqualification may remove automatic cost');
}

console.log('BUSINESS_OPENING_COST_MONTH_LOCK_OK: origin-lock=immutable; destination-lock=immutable; unlocked-edit=allowed; disqualification=origin-lock-aware');
