import fs from 'node:fs';
import vm from 'node:vm';

const src=fs.readFileSync('dist/cloud-adapter.js','utf8');
const start=src.indexOf('vm.logout=async()=>{');
const end=src.indexOf('\n',start);
if(start<0||end<0)throw new Error('BUSINESS_LOGOUT_AUDIT_TRUTHFULNESS_PROBE_FAILED: final logout function missing');
const logoutSource=src.slice(start,end).trim();
const subject={currentUser:{id:'admin',name:'Admin'},auditLogs:[],logAudit(action,detail){this.auditLogs.push({action,detail});},notify(){}};
let failSave=true;
let captured=[];
const context={vm:subject,token:'cookie',revision:1,SESSION_MARKER:'cookie',emptyState(){},rpc:async()=>({}),flushSave:async()=>{if(failSave)throw new Error('SYNTHETIC_SAVE_FAILED');captured=structuredClone(subject.auditLogs);}};
vm.runInNewContext(logoutSource,context,{timeout:1000});
await subject.logout();
const findings=[];
if(subject.auditLogs.filter(x=>x.action==='退出系统').length!==0)findings.push('cancelled logout leaves false exit audit');
failSave=false;
await subject.logout();
if(captured.filter(x=>x.action==='退出系统').length>1)findings.push('retry saves duplicate exit audits');
if(findings.length)throw new Error(`BUSINESS_LOGOUT_AUDIT_TRUTHFULNESS_PROBE_FINDINGS: count=${findings.length}; ${findings.join(' | ')}`);
console.log('BUSINESS_LOGOUT_AUDIT_TRUTHFULNESS_PROBE_SAFE');
