import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=process.cwd();
const appDir=path.join(root,'dist','app');
const adapterPath=path.join(root,'dist','cloud-adapter.js');
if(!fs.existsSync(appDir)||!fs.existsSync(adapterPath))throw new Error('BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_PROBE_FAILED: final artifacts missing');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort();
const bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n');

function extractMethod(name){
  const signature=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m');
  const match=signature.exec(bundle);
  if(!match)throw new Error(`BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_PROBE_FAILED: final runtime ${name} not found`);
  const start=match.index+match[0].indexOf(match[1]);
  const open=bundle.indexOf('{',start);
  let depth=0,quote='',escaped=false,lineComment=false,blockComment=false;
  for(let i=open;i<bundle.length;i+=1){
    const ch=bundle[i],next=bundle[i+1]||'';
    if(lineComment){if(ch==='\n')lineComment=false;continue}
    if(blockComment){if(ch==='*'&&next==='/'){blockComment=false;i+=1}continue}
    if(quote){if(escaped){escaped=false;continue}if(ch==='\\'){escaped=true;continue}if(ch===quote)quote='';continue}
    if(ch==='/'&&next==='/'){lineComment=true;i+=1;continue}
    if(ch==='/'&&next==='*'){blockComment=true;i+=1;continue}
    if(ch==='"'||ch==="'"||ch==='`'){quote=ch;continue}
    if(ch==='{')depth+=1;
    else if(ch==='}'){depth-=1;if(depth===0)return bundle.slice(start,i+1).trim()}
  }
  throw new Error(`BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_PROBE_FAILED: ${name} closing brace missing`);
}

let methods;
try{methods=vm.runInNewContext(`({${['saveOpeningDeal','deleteOpeningDeal'].map(extractMethod).join(',')}})`,{Date,Math,Number,String,Object,Array,JSON,Set,Promise},{timeout:1000})}
catch(error){throw new Error(`BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_PROBE_FAILED: final methods not executable: ${error.message}`)}

const adapter=fs.readFileSync(adapterPath,'utf8');
const bootAnchor='\n  boot();\n})();';
if(adapter.split(bootAnchor).length!==2)throw new Error('BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_PROBE_FAILED: adapter boot anchor drifted');
const harnessAdapter=adapter.replace(bootAnchor,'\n})();');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const clone=value=>JSON.parse(JSON.stringify(value));
const findings=[];
const finding=(ok,label)=>{if(ok)findings.push(label)};
function response(status){return {ok:status>=200&&status<300,status,json:async()=>status>=200&&status<300?({revision:1}):({message:'SYNTHETIC_OPENING_DEAL_SAVE_FAILED'})}}
function parseState(call){const body=JSON.parse(call?.body||'{}');return body.args?.p_state||{}}

const validForm=(overrides={})=>({id:null,clientId:'client-1',externalClientName:'',providerId:'provider-1',contactId:'',partnerName:'',contactName:'',status:'OPENED',effectiveStartDate:'2026-09-01',effectiveEndDate:'',submitDate:'2026-08-20',expectedDate:'2026-09-01',platform:'FB',accountType:'广告账户',adAccountIds:'',quantity:1,fee:100,currency:'USD',notes:'',...overrides});
const deal=(overrides={})=>({...validForm({id:'deal-1'}),...overrides});
const cost=(overrides={})=>({id:'cost-opening-1',date:'2026-09-01',sourceType:'OPENING_DEAL',sourceId:'deal-1',autoGenerated:true,amount:100,currency:'USD',clientId:'client-1',...overrides});

function makeRuntime(kind){
  const calls={fetch:[],notify:[]};
  const subject={};let confirmAction=null,auditId=0,saveAttempt=0,uid=0;
  const localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
  const window={__growthOpsVm:subject,location:{hash:'#account-opening'}};
  const document={documentElement:{classList:{remove:()=>{},add:()=>{}}},body:{appendChild:()=>{}},createElement:()=>({click(){},remove(){}})};
  const fetchMock=async(url,options={})=>{calls.fetch.push({url:String(url),body:String(options.body||'')});saveAttempt+=1;return response(saveAttempt===1?503:200)};
  vm.runInNewContext(harnessAdapter,{window,document,localStorage,URL:{createObjectURL:()=>'',revokeObjectURL:()=>{}},FileReader:class{},Blob,TextEncoder,structuredClone,crypto,console,setTimeout,clearTimeout,Date,Math,JSON,String,Number,Object,Array,Promise,Error,fetch:fetchMock},{timeout:1000});
  const existing=kind==='create'?null:deal();
  Object.assign(subject,methods,{
    currentUser:{id:'finance',name:'Finance User',role:'FINANCE',enabled:true},clients:[],openingProviders:[],openingDeals:existing?[clone(existing)]:[],financeCosts:existing?[cost()]:[],auditLogs:[],backupSnapshots:[],financeReceivables:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],
    openingForm:kind==='create'?validForm():validForm({id:'deal-1',fee:220}),showOpeningModal:true,
    openingProvider:()=>({id:'provider-1',name:'Provider A',contacts:[]}),openingProviderContacts:()=>[],openingContact:()=>null,openingDealUnmatchedIds:()=>[],openingDealMatchedAccounts:()=>[],accountRebateMode:()=> 'CHANNEL',
    localDateKey:()=> '2026-09-02',accountUid:prefix=>`${prefix}-${++uid}`,openingClientName:()=> 'Client A',openingProviderName:()=> 'Provider A',openingContactName:()=> 'Contact A',isMonthLocked:()=>false,
    syncOpeningFeeCost:payload=>{const id=String(payload.id);const idx=subject.financeCosts.findIndex(c=>c.sourceType==='OPENING_DEAL'&&String(c.sourceId)===id);const row={id:idx>-1?subject.financeCosts[idx].id:`cost-${id}`,date:String(payload.effectiveStartDate||payload.expectedDate||'2026-09-01'),sourceType:'OPENING_DEAL',sourceId:id,autoGenerated:true,amount:Number(payload.fee||0),currency:payload.currency||'USD',clientId:payload.clientId||''};if(idx>-1)subject.financeCosts.splice(idx,1,row);else subject.financeCosts.push(row);return 1},
    askConfirm:(_cfg,action)=>{confirmAction=action},logAudit:(action,target)=>{const row={id:`audit-${++auditId}`,action:String(action),target:String(target)};subject.auditLogs.push(row);return row},notify:m=>calls.notify.push(String(m)),ensureDailyBackup:()=>{},
    collectBackupPayload:()=>({clients:[],openingProviders:[],openingDeals:clone(subject.openingDeals),financeCosts:clone(subject.financeCosts),auditLogs:clone(subject.auditLogs),backupSnapshots:[],financeReceivables:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[]}),
  });
  return {subject,calls,existing,getConfirm:()=>confirmAction};
}

// CREATE: current shipped method closes/notifies before the debounced cloud write and
// leaves the deal, linked automatic cost and audit behind after that write returns 503.
{
  const {subject,calls}=makeRuntime('create');
  subject.saveOpeningDeal();
  finding(subject.showOpeningModal===false,'create-success-before-ack');
  await sleep(240);
  finding(subject.openingDeals.length===1&&subject.financeCosts.some(c=>c.sourceType==='OPENING_DEAL')&&subject.auditLogs.some(a=>a.action==='新增客户开户渠道'),'create-failed-save-leaves-local-business-state');
  subject.persist();await sleep(240);const later=parseState(calls.fetch.at(-1));
  finding((later.openingDeals||[]).length===1&&(later.financeCosts||[]).some(c=>c.sourceType==='OPENING_DEAL'),'create-later-persist-resurrects-failed-mutation');
}

// EDIT: a failed save leaves both the edited source row and synchronized linked cost,
// and a later unrelated persist can make the failed edit durable.
{
  const {subject,calls}=makeRuntime('edit');
  subject.saveOpeningDeal();
  finding(subject.showOpeningModal===false,'edit-success-before-ack');
  await sleep(240);
  finding(Number(subject.openingDeals[0]?.fee)===220&&Number(subject.financeCosts[0]?.amount)===220&&subject.auditLogs.some(a=>a.action==='修改客户开户渠道'),'edit-failed-save-leaves-edited-deal+cost+audit');
  subject.persist();await sleep(240);const later=parseState(calls.fetch.at(-1));
  finding(Number(later.openingDeals?.[0]?.fee)===220&&Number(later.financeCosts?.[0]?.amount)===220,'edit-later-persist-resurrects-failed-mutation');
}

// DELETE: after confirmation, source and linked cost disappear and success is emitted
// before ACK; a 503 leaves that false deletion in memory and a later persist commits it.
{
  const {subject,calls,existing,getConfirm}=makeRuntime('delete');
  subject.deleteOpeningDeal(existing);const action=getConfirm();if(typeof action!=='function')throw new Error('BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_PROBE_FAILED: delete confirmation missing');action();
  finding(subject.openingDeals.length===0&&subject.financeCosts.length===0,'delete-success-before-ack');
  await sleep(240);
  finding(subject.openingDeals.length===0&&subject.financeCosts.length===0&&subject.auditLogs.some(a=>a.action==='删除客户开户渠道'),'delete-failed-save-leaves-local-deletion');
  subject.persist();await sleep(240);const later=parseState(calls.fetch.at(-1));
  finding((later.openingDeals||[]).length===0&&(later.financeCosts||[]).length===0,'delete-later-persist-commits-failed-deletion');
}

if(findings.length){
  console.error(`BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_PROBE_FINDINGS: count=${findings.length}`);
  for(const item of findings)console.error(`- ${item}`);
  process.exitCode=1;
}else console.log('BUSINESS_OPENING_DEAL_PERSISTENCE_ACK_PROBE_SAFE');
