import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=process.cwd(),appDir=path.join(root,'dist','app'),adapterPath=path.join(root,'dist','cloud-adapter.js');
if(!fs.existsSync(appDir)||!fs.existsSync(adapterPath))throw new Error('BUSINESS_AD_STRUCTURE_PERSISTENCE_ACK_FAILED: final artifacts missing');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort(),bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n');
function extractMethod(name){const signature=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m'),match=signature.exec(bundle);if(!match)throw new Error(`BUSINESS_AD_STRUCTURE_PERSISTENCE_ACK_FAILED: ${name} missing`);const start=match.index+match[0].indexOf(match[1]),open=bundle.indexOf('{',start);let depth=0,quote='',escaped=false,lineComment=false,blockComment=false;for(let i=open;i<bundle.length;i+=1){const ch=bundle[i],next=bundle[i+1]||'';if(lineComment){if(ch==='\n')lineComment=false;continue}if(blockComment){if(ch==='*'&&next==='/'){blockComment=false;i+=1}continue}if(quote){if(escaped){escaped=false;continue}if(ch==='\\'){escaped=true;continue}if(ch===quote)quote='';continue}if(ch==='/'&&next==='/'){lineComment=true;i+=1;continue}if(ch==='/'&&next==='*'){blockComment=true;i+=1;continue}if(ch==='"'||ch==="'"||ch==='`'){quote=ch;continue}if(ch==='{')depth+=1;else if(ch==='}'&&--depth===0)return bundle.slice(start,i+1).trim()}throw new Error(`BUSINESS_AD_STRUCTURE_PERSISTENCE_ACK_FAILED: ${name} closing brace missing`)}
const names=['addAdCampaign','editAdCampaign','removeAdCampaign','addAdSet','removeAdSet','addCreative','removeCreative'];
let methods;try{methods=vm.runInNewContext(`({${names.map(extractMethod).join(',')}})`,{Date,Math,Number,String,Object,Array,JSON,Set,Promise},{timeout:1000})}catch(error){throw new Error(`BUSINESS_AD_STRUCTURE_PERSISTENCE_ACK_FAILED: methods not executable: ${error.message}`)}
const adapter=fs.readFileSync(adapterPath,'utf8'),bootAnchor='\n  boot();\n})();';if(adapter.split(bootAnchor).length!==2)throw new Error('BUSINESS_AD_STRUCTURE_PERSISTENCE_ACK_FAILED: adapter boot anchor drifted');const harnessAdapter=adapter.replace(bootAnchor,'\n})();');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),clone=v=>JSON.parse(JSON.stringify(v)),fail=m=>{throw new Error('BUSINESS_AD_STRUCTURE_PERSISTENCE_ACK_FAILED: '+m)},ok=(v,m)=>{if(!v)fail(m)},eq=(a,b,m)=>{if(a!==b)fail(`${m}; expected=${b}; actual=${a}`)},same=(a,b,m)=>{if(JSON.stringify(a)!==JSON.stringify(b))fail(`${m}; expected=${JSON.stringify(b)}; actual=${JSON.stringify(a)}`)};
function deferred(){let resolve;const promise=new Promise(r=>{resolve=r});return{promise,resolve}}function response(status){return{ok:status>=200&&status<300,status,json:async()=>status>=200&&status<300?({revision:status}):({message:'SYNTHETIC_AD_STRUCTURE_SAVE_FAILED'})}}function parseState(call){const body=JSON.parse(call?.body||'{}');if(body.rpc!=='crm_save_state')fail(`unexpected rpc=${body.rpc}`);return body.args?.p_state||{}}
const byId=(rows,id)=>Array.isArray(rows)?rows.find(x=>String(x?.id??'')===String(id)):undefined;
function tree(){return{id:'client-1',name:'Client',adCampaigns:[{id:'campaign-1',name:'Campaign',isSaved:true,adSets:[{id:'set-1',name:'Set',ads:[{id:'ad-1',name:'Ad'}]}]}]}}
function makeRuntime({first='fail',withBarrier=true}={}){const calls={fetch:[],notify:[]},subject={},gate=first==='deferred'?deferred():null;let attempt=0,auditSeq=0,campaignSeq=0,setSeq=0,adSeq=0;const window={__growthOpsVm:subject,location:{hash:'#ads'}},document={documentElement:{classList:{remove:()=>{},add:()=>{}}},body:{appendChild:()=>{}},createElement:()=>({click(){},remove(){}})},fetchMock=async(url,options={})=>{calls.fetch.push({url:String(url),body:String(options.body||'')});attempt+=1;if(attempt===1){if(first==='fail')return response(503);if(first==='deferred')return gate.promise}return response(200)};vm.runInNewContext(harnessAdapter,{window,document,localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},URL:{createObjectURL:()=>'',revokeObjectURL:()=>{}},FileReader:class{},Blob,TextEncoder,structuredClone:globalThis.structuredClone,crypto:globalThis.crypto,console,setTimeout,clearTimeout,Date,Math,JSON,String,Number,Object,Array,Promise,Error,fetch:fetchMock},{timeout:1000});if(!withBarrier)delete subject.persistAdStructureBarrier;const client=tree();Object.assign(subject,methods,{clients:[client],selectedAdsClient:client,selectedAdsAccount:{id:'account-1'},currentUser:{id:'admin',name:'Admin',role:'ADMIN',enabled:true},auditLogs:[{id:'audit-existing',action:'EXISTING'}],leads:[],openingProviders:[],openingDeals:[],financeReceivables:[],financeCosts:[],standaloneAlerts:[],dismissedAlerts:[],backupSnapshots:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],mediaTools:[],reminderTypes:[],emptyAdCampaign:()=>({id:`campaign-new-${++campaignSeq}`,name:'',isSaved:false,adSets:[]}),emptyAdSet:()=>({id:`set-new-${++setSeq}`,name:'',ads:[]}),emptyCreative:()=>({id:`ad-new-${++adSeq}`,name:''}),askConfirm:(_o,action)=>{subject.__confirm=action},logAudit:(action,target)=>{const row={id:`audit-${++auditSeq}`,action:String(action),target:String(target)};subject.auditLogs.push(row);return row},notify:m=>calls.notify.push(String(m)),ensureDailyBackup:()=>{},collectBackupPayload:()=>({clients:clone(subject.clients),leads:[],openingProviders:[],openingDeals:[],financeReceivables:[],financeCosts:[],standaloneAlerts:[],dismissedAlerts:[],auditLogs:clone(subject.auditLogs),backupSnapshots:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],mediaTools:[],reminderTypes:[]})});return{subject,client,calls,resolveFirst:status=>gate?.resolve(response(status))}}
function invoke(kind,s){const campaign=s.selectedAdsClient.adCampaigns[0],set=campaign?.adSets?.[0],ad=set?.ads?.[0];if(kind==='campaign-add')return s.addAdCampaign();if(kind==='campaign-edit')return s.editAdCampaign(campaign);if(kind==='campaign-delete'){s.removeAdCampaign(campaign);return s.__confirm?.()}if(kind==='set-add')return s.addAdSet(campaign);if(kind==='set-delete'){s.removeAdSet(campaign,set);return s.__confirm?.()}if(kind==='creative-add')return s.addCreative(set);if(kind==='creative-delete'){s.removeCreative(set,ad);return s.__confirm?.()}fail('unknown kind '+kind)}
async function waitFirstSave(calls){for(let i=0;i<50&&calls.fetch.length===0;i+=1)await sleep(10);eq(calls.fetch.length,1,'exactly one pending ad-structure save before ACK')}async function waitRollback(calls){for(let i=0;i<50&&calls.fetch.length<2;i+=1)await sleep(10);ok(calls.fetch.length>=2,'failed mutation persists rollback truth');return parseState(calls.fetch.at(-1))}async function laterPersist(s,calls){s.persist();await sleep(240);return parseState(calls.fetch.at(-1))}
const successText={"campaign-add":'已添加广告系列',"campaign-edit":'已打开方案编辑器',"campaign-delete":'广告系列已删除',"set-add":'已添加广告组',"set-delete":'广告组已删除',"creative-add":'已添加广告',"creative-delete":'广告已删除'};const hasSuccess=(kind,calls)=>calls.notify.includes(successText[kind]);

// All seven paths serialize tentative state once and hold historical success copy until ACK.
for(const kind of Object.keys(successText)){const {subject,calls,resolveFirst}=makeRuntime({first:'deferred'}),task=invoke(kind,subject);ok(task&&typeof task.then==='function',`${kind} exposes ACK promise`);await waitFirstSave(calls);eq(hasSuccess(kind,calls),false,`${kind} success copy held before ACK`);const pending=parseState(calls.fetch[0]),campaign=byId(pending.clients?.[0]?.adCampaigns,'campaign-1');if(kind==='campaign-add')ok(byId(pending.clients?.[0]?.adCampaigns,'campaign-new-1'),`${kind} tentative row serialized`);if(kind==='campaign-edit')eq(campaign?.isSaved,false,`${kind} tentative field serialized`);if(kind==='campaign-delete')eq(campaign,undefined,`${kind} deletion serialized`);if(kind==='set-add')ok(byId(campaign?.adSets,'set-new-1'),`${kind} tentative row serialized`);if(kind==='set-delete')eq(byId(campaign?.adSets,'set-1'),undefined,`${kind} deletion serialized`);if(kind==='creative-add')ok(byId(byId(campaign?.adSets,'set-1')?.ads,'ad-new-1'),`${kind} tentative row serialized`);if(kind==='creative-delete')eq(byId(byId(campaign?.adSets,'set-1')?.ads,'ad-1'),undefined,`${kind} deletion serialized`);resolveFirst(200);await task;eq(calls.fetch.length,1,`${kind} success uses one durable save`);ok(hasSuccess(kind,calls),`${kind} success copy after ACK`)}

// Failed ACK restores exact prestate, only removes deletion-attempt audits, persists rollback truth,
// and later ordinary persistence cannot resurrect the failed hierarchy change.
for(const kind of Object.keys(successText)){const {subject,calls}=makeRuntime({first:'fail'}),beforeClients=clone(subject.clients),beforeAudits=clone(subject.auditLogs);await invoke(kind,subject);same(subject.clients,beforeClients,`${kind} local rollback clients`);same(subject.auditLogs,beforeAudits,`${kind} local rollback audit truth`);ok(calls.notify.some(m=>m.includes('云端保存失败')),`${kind} failure notice`);const rollback=await waitRollback(calls);same(rollback.clients,beforeClients,`${kind} cloud rollback clients`);same(rollback.auditLogs,beforeAudits,`${kind} cloud rollback audit truth`);const later=await laterPersist(subject,calls);same(later.clients,beforeClients,`${kind} later persist no resurrection`)}

// Newer authority wins over rollback: same-ID campaign replacement, field-level edit, and parent replacement.
{const {subject,calls,resolveFirst}=makeRuntime({first:'deferred'}),task=invoke('campaign-delete',subject);await waitFirstSave(calls);const replacement={id:'campaign-1',name:'Concurrent Campaign',isSaved:true,adSets:[]};subject.selectedAdsClient.adCampaigns.push(replacement);resolveFirst(503);await task;eq(byId(subject.selectedAdsClient.adCampaigns,'campaign-1'),replacement,'campaign replacement preserved');const rollback=await waitRollback(calls);eq(byId(rollback.clients?.[0]?.adCampaigns,'campaign-1')?.name,'Concurrent Campaign','campaign replacement reaches cloud rollback')}
{const {subject,calls,resolveFirst}=makeRuntime({first:'deferred'}),campaign=subject.selectedAdsClient.adCampaigns[0],task=invoke('campaign-edit',subject);await waitFirstSave(calls);campaign.isSaved='CONCURRENT';resolveFirst(503);await task;eq(campaign.isSaved,'CONCURRENT','campaign concurrent field edit preserved');const rollback=await waitRollback(calls);eq(byId(rollback.clients?.[0]?.adCampaigns,'campaign-1')?.isSaved,'CONCURRENT','campaign concurrent field reaches cloud rollback')}
{const {subject,calls,resolveFirst}=makeRuntime({first:'deferred'}),task=invoke('set-add',subject);await waitFirstSave(calls);const replacement={id:'campaign-1',name:'Concurrent Parent',isSaved:true,adSets:[{id:'set-concurrent',name:'New Set',ads:[]}]};subject.selectedAdsClient.adCampaigns.splice(0,1,replacement);resolveFirst(503);await task;eq(subject.selectedAdsClient.adCampaigns[0],replacement,'campaign parent replacement preserved');const rollback=await waitRollback(calls);eq(byId(rollback.clients?.[0]?.adCampaigns,'campaign-1')?.name,'Concurrent Parent','parent replacement reaches cloud rollback')}

// Confirmation is invalidated by selected-client replacement before destructive mutation.
for(const kind of ['campaign-delete','set-delete','creative-delete']){const {subject,client,calls}=makeRuntime({first:'deferred'});const campaign=client.adCampaigns[0],set=campaign.adSets[0],ad=set.ads[0];if(kind==='campaign-delete')subject.removeAdCampaign(campaign);if(kind==='set-delete')subject.removeAdSet(campaign,set);if(kind==='creative-delete')subject.removeCreative(set,ad);ok(typeof subject.__confirm==='function',`${kind} confirmation captured`);const replacement=tree();subject.clients=[replacement];subject.selectedAdsClient=replacement;const result=subject.__confirm();eq(result,undefined,`${kind} replaced-client confirm fails synchronously`);eq(calls.fetch.length,0,`${kind} replaced-client confirm sends zero saves`);same(client,tree(),`${kind} old client remains intact`);ok(calls.notify.some(m=>m.includes('状态已变化')),`${kind} authority-change notice`)}

// Missing durability service fails closed for all seven operations before state/audit/network mutation.
for(const kind of Object.keys(successText)){const {subject,calls}=makeRuntime({first:'deferred',withBarrier:false}),beforeClients=clone(subject.clients),beforeAudits=clone(subject.auditLogs),result=invoke(kind,subject);eq(result,undefined,`${kind} missing barrier synchronous`);same(subject.clients,beforeClients,`${kind} missing barrier preserves clients`);same(subject.auditLogs,beforeAudits,`${kind} missing barrier preserves audits`);eq(calls.fetch.length,0,`${kind} missing barrier zero network`);ok(calls.notify.some(m=>m.includes('持久化服务不可用')),`${kind} missing barrier notice`)}

console.log('BUSINESS_AD_STRUCTURE_PERSISTENCE_ACK_OK: authority=final-app+final-cloud-adapter; campaign+adset+creative add/edit/delete=success-after-single-save-ACK; failure=nested-state+attempt-audit-rollback+rollback-persisted; later-persist=failed-operation-not-resurrected; concurrency=same-id+field+parent-replacement-authoritative; destructive-confirm=selected-client-identity-rechecked; missing-barrier=fail-closed');
