import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=process.cwd();
const appDir=path.join(root,'dist','app');
const adapterPath=path.join(root,'dist','cloud-adapter.js');
if(!fs.existsSync(appDir)||!fs.existsSync(adapterPath))throw new Error('BUSINESS_RECEIVABLE_PERSISTENCE_ACK_FAILED: final artifacts missing');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort();
const bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n');

function extract(name){
  const signature=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m');
  const match=signature.exec(bundle);
  if(!match)throw new Error(`BUSINESS_RECEIVABLE_PERSISTENCE_ACK_FAILED: ${name} missing`);
  const start=match.index+match[0].indexOf(match[1]),tail=bundle.slice(start);
  const defs=[...tail.matchAll(/(?:^|[,]\s*|\n\s*)([A-Za-z_$][A-Za-z0-9_$]*)\s*\([^)]*\)\s*\{/g)];
  if(defs.length<2||defs[0][1]!==name)throw new Error(`BUSINESS_RECEIVABLE_PERSISTENCE_ACK_FAILED: ${name} parser drifted`);
  const next=defs[1].index+defs[1][0].indexOf(defs[1][1]);
  return tail.slice(0,next).replace(/,\s*$/,'').trim();
}

let methods;
try{methods=vm.runInNewContext(`({${['saveReceivable','deleteReceivable'].map(extract).join(',')}})`,{Date,Math,Number,String,Object,Array,JSON,Set,Promise},{timeout:1000})}
catch(error){throw new Error(`BUSINESS_RECEIVABLE_PERSISTENCE_ACK_FAILED: final methods not executable: ${error.message}`)}

const adapter=fs.readFileSync(adapterPath,'utf8');
const bootAnchor='\n  boot();\n})();';
if(adapter.split(bootAnchor).length!==2)throw new Error('BUSINESS_RECEIVABLE_PERSISTENCE_ACK_FAILED: adapter boot anchor drifted');
const harnessAdapter=adapter.replace(bootAnchor,'\n})();');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const fail=message=>{throw new Error('BUSINESS_RECEIVABLE_PERSISTENCE_ACK_FAILED: '+message)};
const ok=(value,label)=>{if(!value)fail(label)};
const eq=(actual,expected,label)=>{if(actual!==expected)fail(`${label}; expected=${expected}; actual=${actual}`)};
function deferred(){let resolve;const promise=new Promise(r=>{resolve=r});return {promise,resolve}}
function response(status){return {ok:status>=200&&status<300,status,json:async()=>status>=200&&status<300?({revision:status}):({message:'SYNTHETIC_RECEIVABLE_SAVE_FAILED'})}}
function parseState(call){const body=JSON.parse(call?.body||'{}');if(body.rpc!=='crm_save_state')fail(`unexpected rpc=${body.rpc}`);return body.args?.p_state}

function makeRuntime({kind,first='fail',withBarrier=true}){
  const calls={fetch:[],notify:[]};
  const subject={};
  let saveAttempt=0,confirmAction=null,auditId=0,uid=0;
  const gate=first==='deferred'?deferred():null;
  const localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
  const window={__growthOpsVm:subject,location:{hash:'#finance'}};
  const document={documentElement:{classList:{remove:()=>{},add:()=>{}}},body:{appendChild:()=>{}},createElement:()=>({click(){},remove(){}})};
  const fetchMock=async(url,options={})=>{
    calls.fetch.push({url:String(url),body:String(options.body||'')});saveAttempt+=1;
    if(saveAttempt===1){if(first==='fail')return response(503);if(first==='deferred')return gate.promise;}
    return response(200);
  };
  vm.runInNewContext(harnessAdapter,{window,document,localStorage,URL:{createObjectURL:()=>'',revokeObjectURL:()=>{}},FileReader:class{},Blob,TextEncoder,structuredClone,crypto,console,setTimeout,clearTimeout,Date,Math,JSON,String,Number,Object,Array,Promise,Error,fetch:fetchMock},{timeout:1000});
  if(!withBarrier)delete subject.persistReceivableBarrier;

  const row=kind==='create'?null:{id:'recv-1',ownerType:'CLIENT',clientId:'c1',payerName:'',settlementMonth:'2026-09',incomeType:'OTHER',projectName:'Original',currency:'USD',amount:100,directCost:20,directCostDate:'2026-09-01',costVendor:'Vendor A',dueDate:'2026-09-30',invoiceStatus:'PENDING',invoiceNo:'',note:'original',payments:[],paidAmount:0,billSource:'MANUAL'};
  const cost=row?{id:'cost-1',date:'2026-09-01',category:'OTHER',scope:'CLIENT',clientId:'c1',currency:'USD',amount:20,vendor:'Vendor A',sourceType:'RECEIVABLE_ITEM',sourceId:'recv-1',autoGenerated:true}:null;
  const form=kind==='create'
    ?{id:null,ownerType:'CLIENT',clientId:'c1',payerName:'',settlementMonth:'2026-09',incomeType:'OTHER',projectName:'New Revenue',currency:'USD',amount:'120',directCost:'30',directCostDate:'2026-09-01',costVendor:'Vendor New',collectionMode:'RECEIVABLE',receivedDate:'2026-09-04',paymentMethod:'银行转账',paymentAccount:'',dueDate:'2026-09-30',invoiceStatus:'PENDING',invoiceNo:'',note:'new',payments:[],billSource:'MANUAL'}
    :{...structuredClone(row),projectName:'Edited Revenue',amount:'150',directCost:'35',costVendor:'Vendor Edited'};

  Object.assign(subject,methods,{
    currentUser:{id:'finance',name:'Finance User',role:'FINANCE',enabled:true},clients:[{id:'c1',name:'Alpha',archived:false}],
    financeReceivables:row?[row]:[],financeCosts:cost?[cost]:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],backupSnapshots:[],auditLogs:[],
    receivableForm:form,showReceivableModal:true,
    assertMonthUnlocked:()=>true,isMonthLocked:()=>false,localDateKey:()=> '2026-09-04',accountUid:prefix=>`${prefix}-${++uid}`,
    normalizeReceivable:r=>{const x=structuredClone(r||{});x.payments=Array.isArray(x.payments)?x.payments:[];x.amount=Number(x.amount||0);x.directCost=Number(x.directCost||0);x.paidAmount=x.payments.reduce((s,p)=>s+Number(p.amount||0),0);return x},
    normalizeFinanceCost:c=>structuredClone(c),financeReceivablePaid:r=>(r?.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0),
    receivableLinkedCost:r=>subject.financeCosts.find(c=>c.sourceType==='RECEIVABLE_ITEM'&&String(c.sourceId)===String(r?.id))||null,
    syncReceivableLinkedCost:r=>{const existing=subject.financeCosts.find(c=>c.sourceType==='RECEIVABLE_ITEM'&&String(c.sourceId)===String(r?.id));if(Number(r?.directCost||0)<=0){if(existing)subject.financeCosts=subject.financeCosts.filter(c=>c!==existing);return existing?1:0}const payload={id:existing?.id||`cost-${++uid}`,date:r.directCostDate||`${r.settlementMonth}-01`,category:'OTHER',scope:'CLIENT',clientId:String(r.clientId||''),currency:r.currency||'USD',amount:Number(r.directCost||0),vendor:r.costVendor||'',sourceType:'RECEIVABLE_ITEM',sourceId:String(r.id),autoGenerated:true};if(existing)Object.assign(existing,payload);else subject.financeCosts.unshift(payload);return 1},
    financeReceivableClientName:()=> 'Alpha',financeIncomeTypeText:()=> '其他收入',financeReceivableMargin:r=>Number(r?.amount||0)-Number(r?.directCost||0),formatMoney:(v,c)=>`${c||'USD'}:${Number(v)}`,
    askConfirm:(_config,action)=>{confirmAction=action},
    logAudit:(action,target)=>{const audit={id:`audit-${++auditId}`,action:String(action),target:String(target)};subject.auditLogs.push(audit);return audit},
    notify:message=>calls.notify.push(String(message)),ensureDailyBackup:()=>{},
    collectBackupPayload:()=>({clients:structuredClone(subject.clients),financeReceivables:structuredClone(subject.financeReceivables),financeCosts:structuredClone(subject.financeCosts),financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],auditLogs:structuredClone(subject.auditLogs),backupSnapshots:[]}),
  });
  return {subject,row,cost,calls,getConfirm:()=>confirmAction,resolveFirst:status=>gate?.resolve(response(status))};
}

async function persistedRollback(calls){await sleep(240);ok(calls.fetch.length>=2,'rollback must itself reach serialized save queue');return parseState(calls.fetch.at(-1))}
async function laterPersist(subject,calls){subject.persist();await sleep(240);return parseState(calls.fetch.at(-1))}

// CREATE failure: tentative row, linked cost and audit are rolled back and cannot be
// resurrected by a later ordinary persist.
{
  const {subject,calls}=makeRuntime({kind:'create',first:'fail'});const task=subject.saveReceivable();ok(task&&typeof task.then==='function','create must expose ACK promise');ok(subject.showReceivableModal,'create modal stays open before ACK');ok(!calls.notify.some(m=>m.includes('收入项目已保存')),'create success held before ACK');await task;
  ok(!subject.financeReceivables.some(r=>r.projectName==='New Revenue'),'failed create removes tentative receivable');ok(!subject.financeCosts.some(c=>String(c.sourceId||'').startsWith('ar-')),'failed create removes tentative linked cost');ok(!subject.auditLogs.some(a=>a.action==='新增收入项目'),'failed create removes attempt audit');ok(calls.notify.some(m=>m.includes('云端保存失败')),'failed create notifies durable failure');
  const rollback=await persistedRollback(calls);ok(!rollback.financeReceivables.some(r=>r.projectName==='New Revenue'),'create rollback cloud state excludes failed receivable');ok(!rollback.auditLogs.some(a=>a.action==='新增收入项目'),'create rollback cloud state excludes false audit');const later=await laterPersist(subject,calls);ok(!later.financeReceivables.some(r=>r.projectName==='New Revenue'),'later persist cannot resurrect failed create');
}

// CREATE success is UI-gated on the actual cloud acknowledgement.
{
  const {subject,calls,resolveFirst}=makeRuntime({kind:'create',first:'deferred'});const task=subject.saveReceivable();ok(subject.financeReceivables.some(r=>r.projectName==='New Revenue'),'create tentative row exists while ACK pending');ok(subject.showReceivableModal,'create modal remains open while ACK pending');ok(!calls.notify.some(m=>m.includes('收入项目已保存')),'create notice held while ACK pending');resolveFirst(200);await task;eq(calls.fetch.length,1,'successful create uses one durable save');eq(subject.showReceivableModal,false,'create modal closes after ACK');ok(calls.notify.some(m=>m.includes('收入项目已保存')),'create notifies only after ACK');
}

// EDIT failure restores the original accounting basis and linked cost.
{
  const {subject,calls}=makeRuntime({kind:'edit',first:'fail'});const task=subject.saveReceivable();ok(task&&typeof task.then==='function','edit must expose ACK promise');ok(subject.showReceivableModal,'edit modal stays open before ACK');await task;const row=subject.financeReceivables.find(r=>r.id==='recv-1'),cost=subject.financeCosts.find(c=>c.sourceId==='recv-1');eq(row.projectName,'Original','failed edit restores project');eq(row.amount,100,'failed edit restores amount');eq(cost.amount,20,'failed edit restores linked cost');ok(!subject.auditLogs.some(a=>a.action==='修改收入项目'),'failed edit removes attempt audit');const rollback=await persistedRollback(calls);eq(rollback.financeReceivables.find(r=>r.id==='recv-1').amount,100,'edit rollback cloud state restores amount');const later=await laterPersist(subject,calls);eq(later.financeReceivables.find(r=>r.id==='recv-1').amount,100,'later persist cannot resurrect failed edit');
}

// EDIT success remains tentative until ACK and closes the modal only afterward.
{
  const {subject,calls,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'});const task=subject.saveReceivable();eq(subject.financeReceivables.find(r=>r.id==='recv-1').amount,150,'edit tentative amount exists while pending');ok(subject.showReceivableModal,'edit modal held open');ok(!calls.notify.some(m=>m.includes('收入项目已保存')),'edit success notice held');resolveFirst(200);await task;eq(calls.fetch.length,1,'successful edit uses one durable save');eq(subject.showReceivableModal,false,'edit modal closes after ACK');ok(calls.notify.some(m=>m.includes('收入项目已保存')),'edit success notice after ACK');
}

// EDIT rollback is attempt-scoped: unrelated concurrent row/cost/audit survive.
{
  const {subject,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'});const task=subject.saveReceivable();const otherRow={id:'recv-other',amount:77,projectName:'Concurrent',payments:[]},otherCost={id:'cost-other',sourceType:'RECEIVABLE_ITEM',sourceId:'recv-other',amount:9},otherAudit={id:'audit-other',action:'并发审计'};subject.financeReceivables.push(otherRow);subject.financeCosts.push(otherCost);subject.auditLogs.push(otherAudit);resolveFirst(503);await task;eq(subject.financeReceivables.find(r=>r.id==='recv-1').amount,100,'concurrent edit failure restores target only');ok(subject.financeReceivables.includes(otherRow),'concurrent row survives edit rollback');ok(subject.financeCosts.includes(otherCost),'concurrent cost survives edit rollback');ok(subject.auditLogs.includes(otherAudit),'concurrent audit survives edit rollback');
}

// Same-ID concurrent replacement is authoritative for both receivable and linked cost.
{
  const {subject,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'});const task=subject.saveReceivable();const replacement={id:'recv-1',ownerType:'CLIENT',clientId:'c1',settlementMonth:'2026-09',incomeType:'OTHER',projectName:'Concurrent Replacement',currency:'USD',amount:888,directCost:66,payments:[]};const replacementCost={id:'cost-replacement',sourceType:'RECEIVABLE_ITEM',sourceId:'recv-1',date:'2026-09-02',amount:66};subject.financeReceivables.splice(0,1,replacement);subject.financeCosts.splice(0,1,replacementCost);resolveFirst(503);await task;eq(subject.financeReceivables.find(r=>r.id==='recv-1'),replacement,'same-ID receivable replacement is not overwritten');eq(subject.financeCosts.find(c=>c.sourceId==='recv-1'),replacementCost,'same-ID linked-cost replacement is not overwritten');
}

// DELETE failure restores the deleted row and linked cost, removes only the attempt
// audit and persists rollback truth so later saves cannot make the failed deletion real.
{
  const {subject,row,calls,getConfirm}=makeRuntime({kind:'delete',first:'fail'});subject.deleteReceivable(row);const confirm=getConfirm();ok(typeof confirm==='function','delete confirmation missing');const task=confirm();ok(task&&typeof task.then==='function','delete callback exposes ACK promise');ok(!calls.notify.some(m=>m.includes('已删除')),'delete success held before ACK');await task;ok(subject.financeReceivables.some(r=>r.id==='recv-1'),'failed delete restores receivable');ok(subject.financeCosts.some(c=>c.sourceId==='recv-1'),'failed delete restores linked cost');ok(!subject.auditLogs.some(a=>a.action==='删除收入项目'),'failed delete removes attempt audit');const rollback=await persistedRollback(calls);ok(rollback.financeReceivables.some(r=>r.id==='recv-1'),'delete rollback cloud state restores receivable');const later=await laterPersist(subject,calls);ok(later.financeReceivables.some(r=>r.id==='recv-1'),'later persist cannot resurrect failed deletion');
}

// DELETE success is ACK-gated.
{
  const {subject,row,calls,getConfirm,resolveFirst}=makeRuntime({kind:'delete',first:'deferred'});subject.deleteReceivable(row);const task=getConfirm()();ok(!subject.financeReceivables.some(r=>r.id==='recv-1'),'delete tentative removal exists while pending');ok(!calls.notify.some(m=>m.includes('已删除')),'delete notice held while pending');resolveFirst(200);await task;eq(calls.fetch.length,1,'successful delete uses one durable save');ok(!subject.financeReceivables.some(r=>r.id==='recv-1'),'successful delete stays removed');ok(calls.notify.some(m=>m.includes('已删除')),'delete notice after ACK');
}

// DELETE rollback merges with unrelated concurrent state.
{
  const {subject,row,getConfirm,resolveFirst}=makeRuntime({kind:'delete',first:'deferred'});subject.deleteReceivable(row);const task=getConfirm()();const otherRow={id:'recv-other',amount:77,payments:[]},otherCost={id:'cost-other',sourceType:'RECEIVABLE_ITEM',sourceId:'recv-other',amount:9},otherAudit={id:'audit-other-delete',action:'并发审计'};subject.financeReceivables.push(otherRow);subject.financeCosts.push(otherCost);subject.auditLogs.push(otherAudit);resolveFirst(503);await task;ok(subject.financeReceivables.some(r=>r.id==='recv-1'),'failed delete restores target beside concurrent row');ok(subject.financeReceivables.includes(otherRow),'delete rollback preserves concurrent row');ok(subject.financeCosts.includes(otherCost),'delete rollback preserves concurrent cost');ok(subject.auditLogs.includes(otherAudit),'delete rollback preserves concurrent audit');
}

// Same-ID replacement appearing while delete ACK is pending wins over stale rollback;
// the old row/cost are not reinserted over it.
{
  const {subject,row,getConfirm,resolveFirst}=makeRuntime({kind:'delete',first:'deferred'});subject.deleteReceivable(row);const task=getConfirm()();const replacement={id:'recv-1',projectName:'Concurrent Replacement',amount:999,payments:[]},replacementCost={id:'cost-replacement',sourceType:'RECEIVABLE_ITEM',sourceId:'recv-1',amount:88};subject.financeReceivables.push(replacement);subject.financeCosts.push(replacementCost);resolveFirst(503);await task;eq(subject.financeReceivables.filter(r=>r.id==='recv-1').length,1,'same-ID delete replacement stays unique');eq(subject.financeReceivables.find(r=>r.id==='recv-1'),replacement,'same-ID delete replacement is authoritative');eq(subject.financeCosts.find(c=>c.sourceId==='recv-1'),replacementCost,'same-ID replacement cost is authoritative');
}

// Missing adapter barrier fails closed rather than falling back to optimistic/debounced
// success. Save rolls back tentative state; delete refuses destructive mutation entirely.
{
  const {subject,calls}=makeRuntime({kind:'create',withBarrier:false});await subject.saveReceivable();ok(!subject.financeReceivables.some(r=>r.projectName==='New Revenue'),'missing create barrier rolls back row');ok(!subject.auditLogs.some(a=>a.action==='新增收入项目'),'missing create barrier removes attempt audit');eq(calls.fetch.length,0,'missing create barrier sends no cloud write');ok(calls.notify.some(m=>m.includes('持久化服务不可用')),'missing create barrier notifies fail-closed');
}
{
  const {subject,calls}=makeRuntime({kind:'edit',withBarrier:false});await subject.saveReceivable();eq(subject.financeReceivables.find(r=>r.id==='recv-1').amount,100,'missing edit barrier restores original amount');eq(subject.financeCosts.find(c=>c.sourceId==='recv-1').amount,20,'missing edit barrier restores original cost');eq(calls.fetch.length,0,'missing edit barrier sends no cloud write');
}
{
  const {subject,row,calls,getConfirm}=makeRuntime({kind:'delete',withBarrier:false});subject.deleteReceivable(row);await getConfirm()();ok(subject.financeReceivables.includes(row),'missing delete barrier leaves row untouched');ok(subject.financeCosts.some(c=>c.sourceId==='recv-1'),'missing delete barrier leaves cost untouched');eq(calls.fetch.length,0,'missing delete barrier sends no cloud write');ok(calls.notify.some(m=>m.includes('持久化服务不可用')),'missing delete barrier notifies fail-closed');
}

console.log('BUSINESS_RECEIVABLE_PERSISTENCE_ACK_OK: authority=final-app+final-cloud-adapter; create+edit+delete=success-after-save-ack; failure=receivable+linked-cost+attempt-audit-rollback+rollback-persisted; later-persist=failed-operation-not-resurrected; concurrency=unrelated-state-preserved+same-id-replacement-authoritative; missing-barrier=fail-closed');
