import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=process.cwd();
const appDir=path.join(root,'dist','app');
const adapterPath=path.join(root,'dist','cloud-adapter.js');
if(!fs.existsSync(appDir)||!fs.existsSync(adapterPath))throw new Error('BUSINESS_FINANCE_COST_PERSISTENCE_ACK_FAILED: final artifacts missing');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort();
const bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n');

function extract(name){
  const signature=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m');
  const match=signature.exec(bundle);
  if(!match)throw new Error(`BUSINESS_FINANCE_COST_PERSISTENCE_ACK_FAILED: ${name} missing`);
  const start=match.index+match[0].indexOf(match[1]),tail=bundle.slice(start);
  const defs=[...tail.matchAll(/(?:^|[,]\s*|\n\s*)([A-Za-z_$][A-Za-z0-9_$]*)\s*\([^)]*\)\s*\{/g)];
  if(defs.length<2||defs[0][1]!==name)throw new Error(`BUSINESS_FINANCE_COST_PERSISTENCE_ACK_FAILED: ${name} parser drifted`);
  const next=defs[1].index+defs[1][0].indexOf(defs[1][1]);
  return tail.slice(0,next).replace(/,\s*$/,'').trim();
}

let methods;
try{methods=vm.runInNewContext(`({${['saveFinanceCost','deleteFinanceCost'].map(extract).join(',')}})`,{Date,Math,Number,String,Object,Array,JSON,Set,Promise},{timeout:1000})}
catch(error){throw new Error(`BUSINESS_FINANCE_COST_PERSISTENCE_ACK_FAILED: final methods not executable: ${error.message}`)}

const adapter=fs.readFileSync(adapterPath,'utf8');
const bootAnchor='\n  boot();\n})();';
if(adapter.split(bootAnchor).length!==2)throw new Error('BUSINESS_FINANCE_COST_PERSISTENCE_ACK_FAILED: adapter boot anchor drifted');
const harnessAdapter=adapter.replace(bootAnchor,'\n})();');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const fail=message=>{throw new Error('BUSINESS_FINANCE_COST_PERSISTENCE_ACK_FAILED: '+message)};
const ok=(value,label)=>{if(!value)fail(label)};
const eq=(actual,expected,label)=>{if(actual!==expected)fail(`${label}; expected=${expected}; actual=${actual}`)};
function deferred(){let resolve;const promise=new Promise(r=>{resolve=r});return {promise,resolve}}
function response(status){return {ok:status>=200&&status<300,status,json:async()=>status>=200&&status<300?({revision:status}):({message:'SYNTHETIC_FINANCE_COST_SAVE_FAILED'})}}
function parseState(call){const body=JSON.parse(call?.body||'{}');if(body.rpc!=='crm_save_state')fail(`unexpected rpc=${body.rpc}`);return body.args?.p_state}

function makeRuntime({kind,first='fail',withBarrier=true}){
  const calls={fetch:[],notify:[]};
  const subject={};
  let saveAttempt=0,confirmAction=null,auditId=0,uid=0;
  const gate=first==='deferred'?deferred():null;
  const localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
  const window={__growthOpsVm:subject,location:{hash:'#finance'}};
  const document={documentElement:{classList:{remove:()=>{},add:()=>{}}},body:{appendChild:()=>{}},createElement:()=>({click(){},remove(){}})};
  const fetchMock=async(url,options={})=>{
    calls.fetch.push({url:String(url),body:String(options.body||'')});saveAttempt+=1;
    if(saveAttempt===1){if(first==='fail')return response(503);if(first==='deferred')return gate.promise;}
    return response(200);
  };
  vm.runInNewContext(harnessAdapter,{window,document,localStorage,URL:{createObjectURL:()=>'',revokeObjectURL:()=>{}},FileReader:class{},Blob,TextEncoder,structuredClone,crypto,console,setTimeout,clearTimeout,Date,Math,JSON,String,Number,Object,Array,Promise,Error,fetch:fetchMock},{timeout:1000});
  if(!withBarrier)delete subject.persistFinanceCostBarrier;

  const existing=kind==='create'?null:{id:'cost-1',date:'2026-09-01',category:'OTHER',scope:'COMPANY',clientId:'',currency:'USD',amount:10,vendor:'Original',note:'original',autoGenerated:false,sourceType:'',sourceId:''};
  const form=kind==='create'
    ?{id:'',date:'2026-09-04',category:'OTHER',scope:'COMPANY',clientId:'',currency:'USD',amount:'25',vendor:'New Vendor',note:'new'}
    :{...structuredClone(existing),date:'2026-09-04',currency:'CNY',amount:'35',vendor:'Edited Vendor',note:'edited'};
  Object.assign(subject,methods,{
    currentUser:{id:'finance',name:'Finance User',role:'FINANCE',enabled:true},clients:[],financeCosts:existing?[existing]:[],auditLogs:[],
    financeReceivables:[],financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],backupSnapshots:[],
    costForm:form,showCostModal:true,
    normalizeFinanceCost:value=>structuredClone(value||{}),assertMonthUnlocked:()=>true,isMonthLocked:()=>false,
    accountUid:prefix=>`${prefix}-${++uid}`,financeCostCategoryText:value=>String(value||''),financeCostScopeText:value=>String(value?.scope||value||''),formatMoney:(value,currency)=>`${currency||'USD'}:${Number(value)}`,
    askConfirm:(_config,action)=>{confirmAction=action},
    logAudit:(action,target)=>{const row={id:`audit-${++auditId}`,action:String(action),target:String(target)};subject.auditLogs.push(row);return row},
    notify:message=>calls.notify.push(String(message)),ensureDailyBackup:()=>{},
    collectBackupPayload:()=>({clients:[],financeReceivables:[],financeCosts:structuredClone(subject.financeCosts),financeMonthLocks:{},financeMonthSnapshots:{},financeReconciliations:[],financeActualRebates:[],auditLogs:structuredClone(subject.auditLogs),backupSnapshots:[]}),
  });
  return {subject,existing,calls,getConfirm:()=>confirmAction,resolveFirst:status=>gate?.resolve(response(status))};
}

async function persistedRollback(calls){await sleep(240);ok(calls.fetch.length>=2,'rollback must itself reach serialized save queue');return parseState(calls.fetch.at(-1))}
async function laterPersist(subject,calls){subject.persist();await sleep(240);return parseState(calls.fetch.at(-1))}

// CREATE failure: tentative cost/audit roll back, rollback truth reaches cloud, and a
// later ordinary persist cannot resurrect the failed accounting mutation.
{
  const {subject,calls}=makeRuntime({kind:'create',first:'fail'});const task=subject.saveFinanceCost();ok(task&&typeof task.then==='function','create must expose ACK promise');ok(subject.financeCosts.some(c=>c.vendor==='New Vendor'),'create tentative cost exists while first save is pending');ok(subject.showCostModal,'create modal stays open before ACK');ok(!calls.notify.some(m=>m.includes('成本已保存')),'create success held before ACK');await task;
  ok(!subject.financeCosts.some(c=>c.vendor==='New Vendor'),'failed create removes tentative cost');ok(!subject.auditLogs.some(a=>a.action==='新增成本'),'failed create removes attempt audit');ok(subject.showCostModal,'failed create keeps modal open');ok(calls.notify.some(m=>m.includes('云端保存失败')),'failed create notifies durable failure');
  const rollback=await persistedRollback(calls);ok(!rollback.financeCosts.some(c=>c.vendor==='New Vendor'),'create rollback cloud state excludes failed cost');ok(!rollback.auditLogs.some(a=>a.action==='新增成本'),'create rollback cloud state excludes false audit');const later=await laterPersist(subject,calls);ok(!later.financeCosts.some(c=>c.vendor==='New Vendor'),'later persist cannot resurrect failed create');
}

// CREATE success is UI-gated on the real cloud acknowledgement.
{
  const {subject,calls,resolveFirst}=makeRuntime({kind:'create',first:'deferred'});const task=subject.saveFinanceCost();ok(subject.financeCosts.some(c=>c.vendor==='New Vendor'),'create tentative cost exists while ACK pending');ok(subject.showCostModal,'create modal remains open while ACK pending');ok(!calls.notify.some(m=>m.includes('成本已保存')),'create notice held while ACK pending');resolveFirst(200);await task;eq(calls.fetch.length,1,'successful create uses one durable save');eq(subject.showCostModal,false,'create modal closes after ACK');ok(calls.notify.some(m=>m.includes('成本已保存')),'create notifies only after ACK');
}

// EDIT failure restores the original accounting basis, removes the false audit, and
// persists the restored truth before any later ordinary save.
{
  const {subject,calls}=makeRuntime({kind:'edit',first:'fail'});const task=subject.saveFinanceCost();ok(task&&typeof task.then==='function','edit must expose ACK promise');eq(subject.financeCosts.find(c=>c.id==='cost-1').amount,35,'edit tentative amount exists before ACK');ok(subject.showCostModal,'edit modal stays open before ACK');await task;const row=subject.financeCosts.find(c=>c.id==='cost-1');eq(row.amount,10,'failed edit restores original amount');eq(row.currency,'USD','failed edit restores original currency');eq(row.vendor,'Original','failed edit restores original vendor');ok(!subject.auditLogs.some(a=>a.action==='修改成本'),'failed edit removes attempt audit');
  const rollback=await persistedRollback(calls);eq(rollback.financeCosts.find(c=>c.id==='cost-1').amount,10,'edit rollback cloud state restores amount');const later=await laterPersist(subject,calls);eq(later.financeCosts.find(c=>c.id==='cost-1').amount,10,'later persist cannot resurrect failed edit');
}

// EDIT success remains tentative until ACK and closes/notifies only afterward.
{
  const {subject,calls,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'});const task=subject.saveFinanceCost();eq(subject.financeCosts.find(c=>c.id==='cost-1').amount,35,'edit tentative amount exists while pending');ok(subject.showCostModal,'edit modal held open');ok(!calls.notify.some(m=>m.includes('成本已保存')),'edit success notice held');resolveFirst(200);await task;eq(calls.fetch.length,1,'successful edit uses one durable save');eq(subject.showCostModal,false,'edit modal closes after ACK');ok(calls.notify.some(m=>m.includes('成本已保存')),'edit success notice after ACK');
}

// EDIT rollback is attempt-scoped: unrelated concurrent cost/audit survive.
{
  const {subject,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'});const task=subject.saveFinanceCost();const otherCost={id:'cost-other',date:'2026-09-04',amount:77,vendor:'Concurrent'},otherAudit={id:'audit-other',action:'并发审计'};subject.financeCosts.push(otherCost);subject.auditLogs.push(otherAudit);resolveFirst(503);await task;eq(subject.financeCosts.find(c=>c.id==='cost-1').amount,10,'concurrent edit failure restores target only');ok(subject.financeCosts.includes(otherCost),'concurrent cost survives edit rollback');ok(subject.auditLogs.includes(otherAudit),'concurrent audit survives edit rollback');
}

// Same-ID concurrent edit replacement is authoritative; stale rollback must not write
// the old cost over a newer same-ID row.
{
  const {subject,resolveFirst}=makeRuntime({kind:'edit',first:'deferred'});const task=subject.saveFinanceCost();const replacement={id:'cost-1',date:'2026-09-04',category:'OTHER',scope:'COMPANY',currency:'EUR',amount:888,vendor:'Concurrent Replacement',autoGenerated:false};subject.financeCosts.splice(0,1,replacement);resolveFirst(503);await task;eq(subject.financeCosts.find(c=>c.id==='cost-1'),replacement,'same-ID edit replacement is not overwritten');
}

// DELETE failure restores the removed cost, removes only the attempt audit, persists
// rollback truth, and prevents a later save from making the failed deletion durable.
{
  const {subject,existing,calls,getConfirm}=makeRuntime({kind:'delete',first:'fail'});subject.deleteFinanceCost(existing);const confirm=getConfirm();ok(typeof confirm==='function','delete confirmation missing');const task=confirm();ok(task&&typeof task.then==='function','delete callback exposes ACK promise');ok(!subject.financeCosts.some(c=>c.id==='cost-1'),'delete tentative removal exists while ACK pending');ok(!calls.notify.some(m=>m.includes('已删除')),'delete success held before ACK');await task;ok(subject.financeCosts.some(c=>c.id==='cost-1'),'failed delete restores cost');ok(!subject.auditLogs.some(a=>a.action==='删除成本'),'failed delete removes attempt audit');ok(calls.notify.some(m=>m.includes('云端保存失败')),'failed delete notifies durable failure');
  const rollback=await persistedRollback(calls);ok(rollback.financeCosts.some(c=>c.id==='cost-1'),'delete rollback cloud state restores cost');ok(!rollback.auditLogs.some(a=>a.action==='删除成本'),'delete rollback cloud state excludes false audit');const later=await laterPersist(subject,calls);ok(later.financeCosts.some(c=>c.id==='cost-1'),'later persist cannot resurrect failed deletion');
}

// DELETE success is held until the acknowledgement resolves.
{
  const {subject,existing,calls,getConfirm,resolveFirst}=makeRuntime({kind:'delete',first:'deferred'});subject.deleteFinanceCost(existing);const task=getConfirm()();ok(!subject.financeCosts.some(c=>c.id==='cost-1'),'delete tentative removal exists while pending');ok(!calls.notify.some(m=>m.includes('已删除')),'delete success notice held');resolveFirst(200);await task;eq(calls.fetch.length,1,'successful delete uses one durable save');ok(!subject.financeCosts.some(c=>c.id==='cost-1'),'successful delete remains removed');ok(calls.notify.some(m=>m.includes('已删除')),'delete success notice after ACK');
}

// DELETE rollback preserves unrelated concurrent state.
{
  const {subject,existing,getConfirm,resolveFirst}=makeRuntime({kind:'delete',first:'deferred'});subject.deleteFinanceCost(existing);const task=getConfirm()();const otherCost={id:'cost-concurrent-delete',amount:19,vendor:'Concurrent'},otherAudit={id:'audit-concurrent-delete',action:'并发审计'};subject.financeCosts.push(otherCost);subject.auditLogs.push(otherAudit);resolveFirst(503);await task;ok(subject.financeCosts.some(c=>c.id==='cost-1'),'delete rollback restores target');ok(subject.financeCosts.includes(otherCost),'delete rollback preserves unrelated cost');ok(subject.auditLogs.includes(otherAudit),'delete rollback preserves unrelated audit');ok(!subject.auditLogs.some(a=>a.action==='删除成本'),'delete rollback removes only attempt audit');
}

// Same-ID concurrent replacement after tentative deletion is authoritative: failed
// rollback must not insert the deleted old row alongside or over the replacement.
{
  const {subject,existing,getConfirm,resolveFirst}=makeRuntime({kind:'delete',first:'deferred'});subject.deleteFinanceCost(existing);const task=getConfirm()();const replacement={id:'cost-1',date:'2026-09-04',category:'OTHER',scope:'COMPANY',currency:'EUR',amount:999,vendor:'Replacement'};subject.financeCosts.push(replacement);resolveFirst(503);await task;eq(subject.financeCosts.filter(c=>c.id==='cost-1').length,1,'same-ID delete replacement remains unique');eq(subject.financeCosts.find(c=>c.id==='cost-1'),replacement,'same-ID delete replacement is not overwritten');
}

// Missing adapter helper fails closed rather than silently degrading to optimistic or
// debounced persistence.
{
  const {subject,calls}=makeRuntime({kind:'create',withBarrier:false});await subject.saveFinanceCost();ok(!subject.financeCosts.some(c=>c.vendor==='New Vendor'),'missing create barrier rolls back cost');ok(!subject.auditLogs.some(a=>a.action==='新增成本'),'missing create barrier rolls back audit');ok(subject.showCostModal,'missing create barrier keeps modal open');ok(calls.notify.some(m=>m.includes('持久化服务不可用')),'missing create barrier notifies fail-closed');
}
{
  const {subject,calls}=makeRuntime({kind:'edit',withBarrier:false});await subject.saveFinanceCost();const row=subject.financeCosts.find(c=>c.id==='cost-1');eq(row.amount,10,'missing edit barrier restores amount');eq(row.currency,'USD','missing edit barrier restores currency');ok(!subject.auditLogs.some(a=>a.action==='修改成本'),'missing edit barrier removes audit');ok(calls.notify.some(m=>m.includes('持久化服务不可用')),'missing edit barrier notifies fail-closed');
}
{
  const {subject,existing,calls,getConfirm}=makeRuntime({kind:'delete',withBarrier:false});subject.deleteFinanceCost(existing);const confirm=getConfirm();ok(typeof confirm==='function','missing delete barrier still requires confirmation');await confirm();ok(subject.financeCosts.includes(existing),'missing delete barrier leaves cost untouched');ok(!subject.auditLogs.some(a=>a.action==='删除成本'),'missing delete barrier creates no audit');ok(calls.notify.some(m=>m.includes('持久化服务不可用')),'missing delete barrier notifies fail-closed');
}

console.log('BUSINESS_FINANCE_COST_PERSISTENCE_ACK_OK: authority=final-app+final-cloud-adapter; create+edit+delete=success-after-save-ack; failure=cost+attempt-audit-rollback+rollback-persisted; later-persist=failed-operation-not-resurrected; concurrency=unrelated-state-preserved+same-id-replacement-authoritative; missing-barrier=fail-closed; automatic-cost-paths=unchanged');
