import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root=process.cwd(),appDir=path.join(root,'dist','app'),adapterPath=path.join(root,'dist','cloud-adapter.js');
if(!fs.existsSync(appDir)||!fs.existsSync(adapterPath))throw new Error('BUSINESS_AD_PLAN_PERSISTENCE_ACK_FAILED: final artifacts missing');
const files=fs.readdirSync(appDir).filter(name=>/^app-inline-\d+\.js$/.test(name)).sort(),bundle=files.map(name=>fs.readFileSync(path.join(appDir,name),'utf8')).join('\n');
function extractMethod(name){const m=new RegExp(`(?:^|[,\\n])\\s*(${name}\\([^)]*\\)\\s*\\{)`,'m').exec(bundle);if(!m)throw new Error(`BUSINESS_AD_PLAN_PERSISTENCE_ACK_FAILED: ${name} missing`);const start=m.index+m[0].indexOf(m[1]),open=bundle.indexOf('{',start);let d=0,q='',esc=false,lc=false,bc=false;for(let i=open;i<bundle.length;i++){const c=bundle[i],n=bundle[i+1]||'';if(lc){if(c==='\n')lc=false;continue}if(bc){if(c==='*'&&n==='/'){bc=false;i++}continue}if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q='';continue}if(c==='/'&&n==='/'){lc=true;i++;continue}if(c==='/'&&n==='*'){bc=true;i++;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return bundle.slice(start,i+1)}throw new Error('BUSINESS_AD_PLAN_PERSISTENCE_ACK_FAILED: method boundary drift')}
const saveAdsPlan=vm.runInNewContext(`({${extractMethod('saveAdsPlan')}}).saveAdsPlan`,{Date,Math,Number,String,Object,Array,JSON,Set,Promise},{timeout:1000});
const adapter=fs.readFileSync(adapterPath,'utf8');if(!adapter.includes('vm.persistAdStructureBarrier=()=>flushSave();'))throw new Error('BUSINESS_AD_PLAN_PERSISTENCE_ACK_FAILED: shared cloud barrier missing');
const clone=v=>JSON.parse(JSON.stringify(v)),fail=m=>{throw new Error('BUSINESS_AD_PLAN_PERSISTENCE_ACK_FAILED: '+m)},ok=(v,m)=>{if(!v)fail(m)},eq=(a,b,m)=>{if(a!==b)fail(`${m}; expected=${b}; actual=${a}`)},same=(a,b,m)=>{if(JSON.stringify(a)!==JSON.stringify(b))fail(`${m}; expected=${JSON.stringify(b)}; actual=${JSON.stringify(a)}`)};
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject}}
function make({mode='ok',withBarrier=true}={}){const gate=deferred(),calls={notify:[],persist:0,barrier:0},campaign={id:'c1',name:'Campaign',planName:'Plan',isSaved:false,savedAt:'',updatedAt:'',adSets:[{id:'s1',name:'Set',ageMin:'20',ageMax:'55',budget:'120.5',ads:[]}]},client={id:'client1',name:'Client',adCampaigns:[campaign]},subject={saveAdsPlan,clients:[client],selectedAdsClient:client,auditLogs:[{id:'old',action:'OLD'}],localDateKey:()=> '2026-09-08',notify:m=>calls.notify.push(String(m)),persist:()=>{calls.persist++},logAudit:(action,target)=>{const row={id:'attempt',action,target};subject.auditLogs.push(row);return row}};if(withBarrier)subject.persistAdStructureBarrier=()=>{calls.barrier++;return mode==='deferred'?gate.promise:mode==='fail'?Promise.reject(new Error('SYNTHETIC_SAVE_FAILED')):Promise.resolve(true)};return{subject,campaign,calls,gate}}

// Success: normalization and audit are tentative, success copy waits for ACK.
{const {subject,campaign,calls,gate}=make({mode:'deferred'}),task=subject.saveAdsPlan(campaign);ok(task&&typeof task.then==='function','save exposes ACK promise');eq(calls.barrier,1,'single durable barrier');eq(campaign.adSets[0].budget,120.5,'budget normalized before save');eq(campaign.adSets[0].ageMin,20,'age min normalized');eq(campaign.isSaved,true,'tentative saved flag');eq(calls.notify.length,0,'success held before ACK');ok(subject.auditLogs.some(x=>x.id==='attempt'),'attempt audit included before ACK');gate.resolve(true);await task;ok(calls.notify.includes('广告方案已保存，并加入方案列表'),'success emitted after ACK');eq(calls.persist,0,'legacy debounced persist suppressed on success')}

// Failure: exact prestate and attempt audit return, then rollback truth is queued.
{const {subject,campaign,calls}=make({mode:'fail'}),before=clone(campaign),beforeAudits=clone(subject.auditLogs);await subject.saveAdsPlan(campaign);same(campaign,before,'failed save restores campaign');same(subject.auditLogs,beforeAudits,'failed save restores audit truth');eq(calls.persist,1,'failed save persists rollback truth');ok(calls.notify.some(x=>x.includes('云端保存失败')),'failure notice explains rollback')}

// Concurrent field authority wins over failure rollback.
{const {subject,campaign,calls,gate}=make({mode:'deferred'}),task=subject.saveAdsPlan(campaign);campaign.updatedAt='CONCURRENT';campaign.isSaved='CONCURRENT';campaign.adSets.push({id:'s2',name:'Concurrent',ageMin:18,ageMax:65,budget:1,ads:[]});gate.reject(new Error('SYNTHETIC_SAVE_FAILED'));await task;eq(campaign.updatedAt,'CONCURRENT','concurrent updatedAt preserved');eq(campaign.isSaved,'CONCURRENT','concurrent saved flag preserved');ok(campaign.adSets.some(x=>x.id==='s2'),'concurrent nested edit preserved');eq(calls.persist,1,'concurrent failure persists current rollback truth')}

// Same-ID replacement and missing durability service fail closed to newer authority.
{const {subject,campaign,gate}=make({mode:'deferred'}),task=subject.saveAdsPlan(campaign),replacement={...clone(campaign),name:'Replacement'};subject.selectedAdsClient.adCampaigns=[replacement];gate.reject(new Error('SYNTHETIC_SAVE_FAILED'));await task;eq(subject.selectedAdsClient.adCampaigns[0],replacement,'same-ID replacement remains authoritative')}
{const {subject,campaign,calls}=make({withBarrier:false}),before=clone(campaign),beforeAudits=clone(subject.auditLogs),result=subject.saveAdsPlan(campaign);eq(result,undefined,'missing barrier returns synchronously');same(campaign,before,'missing barrier preserves campaign');same(subject.auditLogs,beforeAudits,'missing barrier preserves audit');eq(calls.persist,0,'missing barrier performs no persistence');ok(calls.notify.some(x=>x.includes('持久化服务不可用')),'missing barrier notice')}

console.log('BUSINESS_AD_PLAN_PERSISTENCE_ACK_OK: authority=final-app+shared-cloud-barrier; save=validation+normalization+audit+success-after-ACK; failure=field-level+attempt-audit-rollback+rollback-persisted; concurrency=nested-field+same-id-replacement-authoritative; missing-barrier=fail-closed');
