-- SUPERSEDED TIMESTAMP — DO NOT EXECUTE.
-- Production recorded this change as migration version 20260830071649.
-- The authoritative rollback is:
--   supabase/rollback/20260830071649_client_account_safe_summary_correspondence.sql
--
-- This marker is intentionally non-executable so the historical PR filename cannot
-- be mistaken for the Production migration-ledger authority.
